"use server";

import { revalidatePath } from "next/cache";
import { createClient as createSupabaseClient } from "@/lib/supabase/server";
import { isSupabaseConfigured } from "@/lib/supabase/config";
import { field, optionalField, readableError, requiredText, type ActionState } from "@/lib/forms";

async function getUserClient(): Promise<{ supabase: Awaited<ReturnType<typeof createSupabaseClient>> } | { error: string }> { if (!isSupabaseConfigured()) return { error: "Supabase is not configured." }; const supabase = await createSupabaseClient(); const { data: { user } } = await supabase.auth.getUser(); return user ? { supabase } : { error: "Your session has expired. Sign in again." }; }
export async function createReminderAction(_previous: ActionState, formData: FormData): Promise<ActionState> { const message = requiredText(formData, "message", "Reminder", 1000); const dueAt = field(formData, "due_at"); if (typeof message !== "string") return message; if (!dueAt || Number.isNaN(new Date(`${dueAt}:00Z`).getTime())) return { error: "Choose a valid reminder time." }; const auth = await getUserClient(); if ("error" in auth) return auth; const { error } = await auth.supabase.from("reminders").insert({ kind: "custom", due_at: new Date(`${dueAt}:00Z`).toISOString(), message, subject_type: optionalField(formData, "subject_type"), subject_id: optionalField(formData, "subject_id") }); if (error) return { error: readableError(error.message) }; revalidatePath("/reminders"); revalidatePath("/"); return { success: "Reminder created." }; }
export async function completeReminderAction(_previous: ActionState, formData: FormData): Promise<ActionState> { const id = field(formData, "id"); if (!id) return { error: "Reminder ID is missing." }; const auth = await getUserClient(); if ("error" in auth) return auth; const { error } = await auth.supabase.from("reminders").update({ done: true }).eq("id", id); if (error) return { error: readableError(error.message) }; revalidatePath("/reminders"); return { success: "Reminder completed." }; }
export async function deleteReminderAction(_previous: ActionState, formData: FormData): Promise<ActionState> { const id = field(formData, "id"); if (!id) return { error: "Reminder ID is missing." }; const auth = await getUserClient(); if ("error" in auth) return auth; const { error } = await auth.supabase.from("reminders").delete().eq("id", id); if (error) return { error: readableError(error.message) }; revalidatePath("/reminders"); return { success: "Reminder removed." }; }
