import type { Metadata } from "next";
import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { isSupabaseConfigured } from "@/lib/supabase/config";
import { isMissingTable } from "@/lib/forms";
import { PageHeader } from "@/components/page-header";
import { FormSection } from "@/components/form-controls";
import { MigrationsRequired, SetupRequired } from "@/components/states";
import { CompleteReminderForm, DeleteReminderForm, ReminderForm } from "./reminder-forms";

export const metadata: Metadata = { title: "Reminders" };
export const dynamic = "force-dynamic";
function shift(date: string, days: number): string { const result = new Date(`${date}T00:00:00Z`); result.setUTCDate(result.getUTCDate() + days); return result.toISOString().slice(0, 10); }
type SystemReminder = { id: string; kind: string; message: string; due: string; href: string };
export default async function RemindersPage() {
  if (!isSupabaseConfigured()) return <SetupRequired />; const supabase = await createClient(); await supabase.rpc("refresh_invoice_statuses"); const today = new Date().toISOString().slice(0, 10); const soon = shift(today, 3); const deadline = shift(today, 14);
  const [tasksResponse, overdueTasksResponse, waitingResponse, quotesResponse, contractsResponse, invoicesResponse, projectsResponse, customResponse, weeklyResponse, overridesResponse, scheduledTasksResponse, workBlocksResponse, clientsResponse, communicationsResponse] = await Promise.all([
    supabase.from("tasks").select("id, title, due_date, status").in("status", ["todo", "in_progress", "blocked_other"]).gte("due_date", today).lt("due_date", soon).order("due_date"),
    supabase.from("tasks").select("id, title, due_date").in("status", ["todo", "in_progress", "blocked_waiting_client", "blocked_other"]).lt("due_date", today).order("due_date", { ascending: true, nullsFirst: false }),
    supabase.from("tasks").select("id, title, due_date").eq("status", "blocked_waiting_client").order("due_date", { ascending: true, nullsFirst: false }),
    supabase.from("quotes").select("id, number, title, valid_until, status").in("status", ["sent", "viewed"]).order("valid_until", { ascending: true, nullsFirst: false }),
    supabase.from("contracts").select("id, title, status, token_expires_at").eq("status", "sent").order("created_at"),
    supabase.from("invoices").select("id, number, due_on, status, balance_cents").in("status", ["sent", "partially_paid", "overdue"]).order("due_on"),
    supabase.from("projects").select("id, name, deadline, status").in("status", ["planning", "active", "on_hold"]).is("deleted_at", null).gte("deadline", today).lt("deadline", deadline).order("deadline"),
    supabase.from("reminders").select("id, message, due_at, done, kind").eq("done", false).order("due_at"),
    supabase.from("weekly_capacity").select("weekday, available_minutes"),
    supabase.from("workday_capacity").select("date, available_minutes").gte("date", today).lt("date", deadline),
    supabase.from("tasks").select("scheduled_date, estimated_minutes, status").gte("scheduled_date", today).lt("scheduled_date", deadline).not("status", "in", "(done,cancelled)"),
    supabase.from("calendar_events").select("starts_at, ends_at, task_id, type").eq("type", "work_block").gte("starts_at", `${today}T00:00:00Z`).lt("starts_at", `${deadline}T00:00:00Z`),
    supabase.from("clients").select("id, name, status").in("status", ["lead", "active"]).is("deleted_at", null),
    supabase.from("communications").select("client_id, direction, occurred_at").gte("occurred_at", `${shift(today, -30)}T00:00:00Z`).order("occurred_at", { ascending: false }).limit(1000),
  ]);
  const responses = [tasksResponse, overdueTasksResponse, waitingResponse, quotesResponse, contractsResponse, invoicesResponse, projectsResponse, customResponse, weeklyResponse, overridesResponse, scheduledTasksResponse, workBlocksResponse, clientsResponse, communicationsResponse]; if (responses.some((response) => response.error && isMissingTable(response.error.message))) return <MigrationsRequired />; const failed = responses.find((response) => response.error); if (failed?.error) throw new Error(failed.error.message);
  const dueTasks = (tasksResponse.data ?? []) as { id: string; title: string; due_date: string; status: string }[]; const overdueTasks = (overdueTasksResponse.data ?? []) as { id: string; title: string; due_date: string }[]; const waiting = (waitingResponse.data ?? []) as { id: string; title: string; due_date: string | null }[]; const quotes = (quotesResponse.data ?? []) as { id: string; number: string; title: string; valid_until: string | null; status: string }[]; const contracts = (contractsResponse.data ?? []) as { id: string; title: string; status: string; token_expires_at: string | null }[]; const invoices = (invoicesResponse.data ?? []) as { id: string; number: string; due_on: string; status: string; balance_cents: number }[]; const projects = (projectsResponse.data ?? []) as { id: string; name: string; deadline: string; status: string }[]; const custom = (customResponse.data ?? []) as { id: string; message: string; due_at: string; done: boolean; kind: string }[]; const clients = (clientsResponse.data ?? []) as { id: string; name: string; status: string }[]; const communications = (communicationsResponse.data ?? []) as { client_id: string; direction: string; occurred_at: string }[]; const weekly = (weeklyResponse.data ?? []) as { weekday: number; available_minutes: number }[]; const overrides = (overridesResponse.data ?? []) as { date: string; available_minutes: number }[]; const scheduledTasks = (scheduledTasksResponse.data ?? []) as { scheduled_date: string; estimated_minutes: number | null; status: string }[]; const workBlocks = (workBlocksResponse.data ?? []) as { starts_at: string; ends_at: string; task_id: string | null; type: string }[];
  const weeklyMap = new Map(weekly.map((item) => [item.weekday, item.available_minutes])); const overrideMap = new Map(overrides.map((item) => [item.date, item.available_minutes])); const system: SystemReminder[] = []; const dayLabel = (date: string) => new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(date.includes("T") ? date : `${date}T00:00:00Z`));
  overdueTasks.forEach((task) => system.push({ id: `overdue-${task.id}`, kind: "Overdue task", message: task.title, due: task.due_date, href: `/tasks/${task.id}` })); dueTasks.forEach((task) => system.push({ id: `due-${task.id}`, kind: "Task due soon", message: task.title, due: task.due_date, href: `/tasks/${task.id}` })); waiting.forEach((task) => system.push({ id: `waiting-${task.id}`, kind: "Waiting on client", message: task.title, due: task.due_date ?? today, href: `/tasks/${task.id}` })); quotes.forEach((quote) => system.push({ id: `quote-${quote.id}`, kind: "Quote awaiting response", message: `${quote.number} · ${quote.title}`, due: quote.valid_until ?? today, href: `/quotes/${quote.id}` })); contracts.forEach((contract) => system.push({ id: `contract-${contract.id}`, kind: "Unsigned contract", message: contract.title, due: contract.token_expires_at?.slice(0, 10) ?? today, href: `/contracts/${contract.id}` })); invoices.forEach((invoice) => system.push({ id: `invoice-${invoice.id}`, kind: invoice.status === "overdue" || invoice.due_on < today ? "Invoice overdue" : "Invoice due", message: invoice.number, due: invoice.due_on, href: `/invoices/${invoice.id}` })); projects.forEach((project) => system.push({ id: `project-${project.id}`, kind: "Project deadline approaching", message: project.name, due: project.deadline, href: `/projects/${project.id}` }));
  const cutoff = new Date(`${shift(today, -3)}T00:00:00Z`).getTime();
  clients.forEach((client) => {
    const clientComms = communications.filter((item) => item.client_id === client.id).sort((a, b) => b.occurred_at.localeCompare(a.occurred_at));
    const latest = clientComms[0];
    if (latest && latest.direction === "out" && new Date(latest.occurred_at).getTime() <= cutoff) system.push({ id: `client-${client.id}`, kind: "Client response overdue", message: `${client.name} has not responded to the latest outgoing contact`, due: latest.occurred_at, href: `/clients/${client.id}` });
  });
  for (let cursor = today; cursor < deadline; cursor = shift(cursor, 1)) { const weekday = new Date(`${cursor}T00:00:00Z`).getUTCDay(); const available = overrideMap.get(cursor) ?? weeklyMap.get(weekday) ?? 480; const scheduled = scheduledTasks.filter((task) => task.scheduled_date === cursor).reduce((sum, task) => sum + (task.estimated_minutes ?? 0), 0) + workBlocks.filter((event) => !event.task_id && event.starts_at.slice(0, 10) === cursor).reduce((sum, event) => sum + Math.max(0, (new Date(event.ends_at).getTime() - new Date(event.starts_at).getTime()) / 60000), 0); if (scheduled > available) system.push({ id: `overload-${cursor}`, kind: "Schedule overloaded", message: `${dayLabel(cursor)} · ${Math.round(scheduled / 60 * 10) / 10} scheduled / ${Math.round(available / 60 * 10) / 10} available hours`, due: cursor, href: "/workload" }); }
  system.sort((a, b) => a.due.localeCompare(b.due));
  return <><PageHeader title="Reminders" description="Live reminders derived from your tasks, sales records, deadlines, workload, and custom reminder rows. Nothing is mocked or silently scheduled." /><div className="flex flex-wrap gap-4 text-sm"><Link href="/workload" className="underline decoration-border underline-offset-4">Review workload</Link><Link href="/calendar" className="underline decoration-border underline-offset-4">Open calendar</Link></div><FormSection title="System reminders" description="These are calculated from current database records each time this page loads.">{system.length === 0 ? <p className="text-sm text-muted-foreground">No active system reminders.</p> : <ul className="divide-y divide-border border-y border-border">{system.map((item) => <li key={item.id} className="flex flex-wrap items-start justify-between gap-4 py-4"><div><p className="text-xs font-medium uppercase tracking-widest text-muted-foreground">{item.kind}</p><Link href={item.href} className="mt-1 block font-medium underline decoration-border underline-offset-4">{item.message}</Link></div><span className="text-sm text-muted-foreground">{dayLabel(item.due)}</span></li>)}</ul>}</FormSection><FormSection title="Custom reminders" description="Use these for follow-ups or any date-specific item outside the automatic triggers."><ReminderForm />{custom.length ? <div className="mt-8 divide-y divide-border border-y border-border">{custom.map((item) => <div key={item.id} className="flex flex-wrap items-start justify-between gap-4 py-4"><div><p className="font-medium">{item.message}</p><p className="mt-1 text-xs text-muted-foreground">Due {new Date(item.due_at).toLocaleString()}</p></div><div className="flex items-center gap-4"><CompleteReminderForm id={item.id} /><DeleteReminderForm id={item.id} /></div></div>)}</div> : null}</FormSection></>;
}
