"use server";

import { revalidatePath } from "next/cache";
import { createClient as createSupabaseClient } from "@/lib/supabase/server";
import { isSupabaseConfigured } from "@/lib/supabase/config";
import { field, optionalDate, optionalField, readableError, requiredText, type ActionState } from "@/lib/forms";

async function getUserClient(): Promise<{ supabase: Awaited<ReturnType<typeof createSupabaseClient>> } | { error: string }> { if (!isSupabaseConfigured()) return { error: "Supabase is not configured." }; const supabase = await createSupabaseClient(); const { data: { user } } = await supabase.auth.getUser(); return user ? { supabase } : { error: "Your session has expired. Sign in again." }; }
function money(value: string, label: string): number | ActionState { if (!value) return 0; const amount = Number(value); if (!Number.isFinite(amount) || amount < 0 || amount > 100000000) return { error: `${label} must be a valid non-negative amount.` }; return Math.round(amount * 100); }
type Line = { description: string; qty: number; unit_amount_cents: number; amount_cents: number; sort_order: number };
function lines(formData: FormData): Line[] | ActionState {
  const raw = field(formData, "line_items");
  if (!raw) return { error: "Add at least one invoice line item." };
  let parsed: unknown;
  try { parsed = JSON.parse(raw); } catch { return { error: "Invoice line items are invalid." }; }
  if (!Array.isArray(parsed) || parsed.length === 0 || parsed.length > 100) return { error: "Add between one and one hundred line items." };
  const result: Line[] = [];
  for (const [index, item] of parsed.entries()) {
    if (!item || typeof item !== "object") return { error: `Line item ${index + 1} is invalid.` };
    const row = item as Record<string, unknown>;
    const description = String(row.description ?? "").trim();
    const qty = Number(row.qty);
    const unit = Number(row.unit_amount);
    if (!description || description.length > 500 || !Number.isFinite(qty) || qty <= 0 || qty > 1000000 || !Number.isFinite(unit) || unit < 0 || unit > 100000000) return { error: `Line item ${index + 1} is invalid.` };
    const cents = Math.round(unit * 100);
    result.push({ description, qty, unit_amount_cents: cents, amount_cents: Math.round(qty * cents), sort_order: index });
  }
  return result;
}
function invoiceValues(formData: FormData): { values: Record<string, unknown>; lines: Line[] } | ActionState { const title = requiredText(formData, "title", "Invoice title", 200); const number = requiredText(formData, "number", "Invoice number", 80); const clientId = field(formData, "client_id"); if (typeof title !== "string") return title; if (typeof number !== "string") return number; if (!clientId) return { error: "Choose a client." }; const status = field(formData, "status") || "draft"; if (!["draft", "sent", "partially_paid", "paid", "overdue", "void"].includes(status)) return { error: "Choose a valid invoice status." }; const invoiceLines = lines(formData); if (!Array.isArray(invoiceLines)) return invoiceLines; const discount = money(field(formData, "discount_amount"), "Discount"); const tax = money(field(formData, "tax_amount"), "Tax"); const deposit = money(field(formData, "deposit_amount"), "Deposit"); if (typeof discount !== "number") return discount; if (typeof tax !== "number") return tax; if (typeof deposit !== "number") return deposit; const subtotal = invoiceLines.reduce((sum, item) => sum + item.amount_cents, 0); if (discount > subtotal) return { error: "Discount cannot exceed subtotal." }; const currency = (field(formData, "currency") || "USD").toUpperCase(); if (!/^[A-Z]{3}$/.test(currency)) return { error: "Currency must be a three-letter code such as USD." }; const total = subtotal - discount + tax; return { values: { client_id: clientId, project_id: optionalField(formData, "project_id"), quote_id: optionalField(formData, "quote_id"), contract_id: optionalField(formData, "contract_id"), number, title, status, issued_on: optionalDate(formData, "issued_on") ?? new Date().toISOString().slice(0, 10), due_on: optionalDate(formData, "due_on") ?? new Date().toISOString().slice(0, 10), currency, subtotal_cents: subtotal, discount_cents: discount, tax_cents: tax, total_cents: total, deposit_cents: deposit, paid_cents: 0, balance_cents: total }, lines: invoiceLines }; }
async function replaceLines(supabase: Awaited<ReturnType<typeof createSupabaseClient>>, invoiceId: string, invoiceLines: Line[]): Promise<string | null> { const removed = await supabase.from("invoice_line_items").delete().eq("invoice_id", invoiceId); if (removed.error) return removed.error.message; const inserted = await supabase.from("invoice_line_items").insert(invoiceLines.map((line) => ({ ...line, invoice_id: invoiceId }))); return inserted.error?.message ?? null; }
export async function createInvoiceAction(_previous: ActionState, formData: FormData): Promise<ActionState> { const parsed = invoiceValues(formData); if (!("values" in parsed)) return parsed; const auth = await getUserClient(); if ("error" in auth) return auth; const { data, error } = await auth.supabase.from("invoices").insert(parsed.values).select("id").single(); if (error) return { error: readableError(error.message) }; const lineError = await replaceLines(auth.supabase, data.id, parsed.lines); if (lineError) return { error: readableError(lineError) }; revalidatePath("/invoices"); revalidatePath("/"); return { success: "Invoice created." }; }
export async function updateInvoiceAction(_previous: ActionState, formData: FormData): Promise<ActionState> { const id = field(formData, "id"); if (!id) return { error: "Invoice ID is missing." }; const parsed = invoiceValues(formData); if (!("values" in parsed)) return parsed; const auth = await getUserClient(); if ("error" in auth) return auth; const current = await auth.supabase.from("invoices").select("paid_cents").eq("id", id).maybeSingle(); if (current.error) return { error: readableError(current.error.message) }; const paidCents = current.data?.paid_cents ?? 0; if (Number(parsed.values.total_cents) < paidCents) return { error: "Invoice total cannot be lower than payments already recorded." }; const values = { ...parsed.values, paid_cents: paidCents, balance_cents: Number(parsed.values.total_cents) - paidCents }; const { error } = await auth.supabase.from("invoices").update(values).eq("id", id); if (error) return { error: readableError(error.message) }; const lineError = await replaceLines(auth.supabase, id, parsed.lines); if (lineError) return { error: readableError(lineError) }; revalidatePath("/invoices"); revalidatePath(`/invoices/${id}`); revalidatePath("/"); return { success: "Invoice saved." }; }
export async function deleteInvoiceAction(_previous: ActionState, formData: FormData): Promise<ActionState> { const id = field(formData, "id"); if (!id) return { error: "Invoice ID is missing." }; const auth = await getUserClient(); if ("error" in auth) return auth; const { error } = await auth.supabase.from("invoices").delete().eq("id", id); if (error) return { error: readableError(error.message) }; revalidatePath("/invoices"); return { success: "Invoice deleted." }; }
export async function recordPaymentAction(_previous: ActionState, formData: FormData): Promise<ActionState> { const invoiceId = field(formData, "invoice_id"); if (!invoiceId) return { error: "Invoice ID is missing." }; const amount = money(field(formData, "amount"), "Payment amount"); if (typeof amount !== "number" || amount <= 0) return { error: "Payment amount must be greater than zero." }; const method = field(formData, "method") || "other"; const kind = field(formData, "kind") || "partial"; if (!["bank_transfer", "cash", "card", "other"].includes(method)) return { error: "Choose a valid manual payment method." }; if (!["deposit", "partial", "full"].includes(kind)) return { error: "Choose a valid payment kind." }; const auth = await getUserClient(); if ("error" in auth) return auth; const invoice = await auth.supabase.from("invoices").select("total_cents, paid_cents").eq("id", invoiceId).maybeSingle(); if (invoice.error) return { error: readableError(invoice.error.message) }; if (!invoice.data) return { error: "Invoice not found." }; if (amount > invoice.data.total_cents - invoice.data.paid_cents) return { error: "Payment cannot exceed the remaining balance." }; const { error } = await auth.supabase.from("payments").insert({ invoice_id: invoiceId, amount_cents: amount, paid_on: optionalDate(formData, "paid_on") ?? new Date().toISOString().slice(0, 10), method, kind, reference: optionalField(formData, "reference"), note: optionalField(formData, "note") }); if (error) return { error: readableError(error.message) }; revalidatePath("/invoices"); revalidatePath(`/invoices/${invoiceId}`); revalidatePath("/"); return { success: "Payment recorded." }; }
export async function deletePaymentAction(_previous: ActionState, formData: FormData): Promise<ActionState> { const id = field(formData, "id"); const invoiceId = field(formData, "invoice_id"); if (!id || !invoiceId) return { error: "Payment details are missing." }; const auth = await getUserClient(); if ("error" in auth) return auth; const { error } = await auth.supabase.from("payments").delete().eq("id", id); if (error) return { error: readableError(error.message) }; revalidatePath("/invoices"); revalidatePath(`/invoices/${invoiceId}`); return { success: "Payment removed." }; }
