"use server";

import { revalidatePath } from "next/cache";
import { createClient as createSupabaseClient } from "@/lib/supabase/server";
import { isSupabaseConfigured } from "@/lib/supabase/config";
import { field, optionalField, readableError, requiredText, type ActionState } from "@/lib/forms";

async function getUserClient(): Promise<{ supabase: Awaited<ReturnType<typeof createSupabaseClient>> } | { error: string }> { if (!isSupabaseConfigured()) return { error: "Supabase is not configured." }; const supabase = await createSupabaseClient(); const { data: { user } } = await supabase.auth.getUser(); return user ? { supabase } : { error: "Your session has expired. Sign in again." }; }
function dateTime(value: string, label: string): string | ActionState { const parsed = new Date(value.endsWith("Z") ? value : `${value}:00Z`); if (Number.isNaN(parsed.getTime())) return { error: `${label} is invalid.` }; return parsed.toISOString(); }
function eventValues(formData: FormData): ActionState | Record<string, unknown> { const title = requiredText(formData, "title", "Event title", 240); if (typeof title !== "string") return title; const type = field(formData, "type") || "meeting"; if (!["meeting", "work_block", "other"].includes(type)) return { error: "Choose a valid event type." }; const starts = dateTime(field(formData, "starts_at"), "Start time"); const ends = dateTime(field(formData, "ends_at"), "End time"); if (typeof starts !== "string") return starts; if (typeof ends !== "string") return ends; if (new Date(ends) <= new Date(starts)) return { error: "End time must be after start time." }; return { title, type, starts_at: starts, ends_at: ends, client_id: optionalField(formData, "client_id"), project_id: optionalField(formData, "project_id"), task_id: optionalField(formData, "task_id"), notes: optionalField(formData, "notes") }; }
export async function createCalendarEventAction(_previous: ActionState, formData: FormData): Promise<ActionState> { const values = eventValues(formData); if ("error" in values) return values; const auth = await getUserClient(); if ("error" in auth) return auth; const { error } = await auth.supabase.from("calendar_events").insert(values); if (error) return { error: readableError(error.message) }; revalidatePath("/calendar"); revalidatePath("/workload"); revalidatePath("/"); return { success: "Calendar item created." }; }
export async function updateCalendarEventAction(_previous: ActionState, formData: FormData): Promise<ActionState> { const id = field(formData, "id"); if (!id) return { error: "Calendar item ID is missing." }; const values = eventValues(formData); if ("error" in values) return values; const auth = await getUserClient(); if ("error" in auth) return auth; const { error } = await auth.supabase.from("calendar_events").update(values).eq("id", id); if (error) return { error: readableError(error.message) }; revalidatePath("/calendar"); revalidatePath("/workload"); revalidatePath("/"); return { success: "Calendar item saved." }; }
export async function deleteCalendarEventAction(_previous: ActionState, formData: FormData): Promise<ActionState> { const id = field(formData, "id"); if (!id) return { error: "Calendar item ID is missing." }; const auth = await getUserClient(); if ("error" in auth) return auth; const { error } = await auth.supabase.from("calendar_events").delete().eq("id", id); if (error) return { error: readableError(error.message) }; revalidatePath("/calendar"); revalidatePath("/workload"); return { success: "Calendar item removed." }; }
export async function rescheduleTaskAction(_previous: ActionState, formData: FormData): Promise<ActionState> { const id = field(formData, "task_id"); if (!id) return { error: "Task ID is missing." }; const date = optionalField(formData, "scheduled_date"); if (date && !/^\d{4}-\d{2}-\d{2}$/.test(date)) return { error: "Planned date is invalid." }; const auth = await getUserClient(); if ("error" in auth) return auth; const { error } = await auth.supabase.from("tasks").update({ scheduled_date: date }).eq("id", id); if (error) return { error: readableError(error.message) }; revalidatePath("/calendar"); revalidatePath("/workload"); revalidatePath("/tasks"); revalidatePath("/"); return { success: date ? "Task scheduled." : "Task unscheduled." }; }
