"use client";

import { useActionState } from "react";
import type { ReactNode } from "react";
import type { ActionState } from "@/lib/forms";
import { createCalendarEventAction, deleteCalendarEventAction, rescheduleTaskAction, updateCalendarEventAction } from "./actions";
import { FieldLabel, FormMessage, SelectInput, SubmitButton, TextArea, TextInput } from "@/components/form-controls";
const initialState: ActionState = {};
type Option = { id: string; label: string };
type Event = { id: string; title: string; type: string; starts_at: string; ends_at: string; client_id: string | null; project_id: string | null; task_id: string | null; notes: string | null };
function Shell({ title, children }: { title: string; children: ReactNode }) { return <div className="border-t border-border pt-6"><h2 className="text-sm font-medium">{title}</h2><div className="mt-4">{children}</div></div>; }
function EventFields({ clients, projects, tasks, event }: { clients: Option[]; projects: Option[]; tasks: Option[]; event?: Event }) { const input = (value: string | null) => value ? new Date(value).toISOString().slice(0, 16) : ""; return <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><div><FieldLabel label="Title" htmlFor="event-title" required /><TextInput id="event-title" name="title" required defaultValue={event?.title} placeholder="Client kickoff" /></div><div><FieldLabel label="Type" htmlFor="event-type" required /><SelectInput id="event-type" name="type" required defaultValue={event?.type ?? "meeting"}><option value="meeting">Meeting</option><option value="work_block">Planned work block</option><option value="other">Other</option></SelectInput></div><div><FieldLabel label="Starts" htmlFor="event-starts" required /><TextInput id="event-starts" name="starts_at" type="datetime-local" required defaultValue={input(event?.starts_at ?? null)} /></div><div><FieldLabel label="Ends" htmlFor="event-ends" required /><TextInput id="event-ends" name="ends_at" type="datetime-local" required defaultValue={input(event?.ends_at ?? null)} /></div><div><FieldLabel label="Client" htmlFor="event-client" /><SelectInput id="event-client" name="client_id" defaultValue={event?.client_id}><option value="">No client</option>{clients.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</SelectInput></div><div><FieldLabel label="Project" htmlFor="event-project" /><SelectInput id="event-project" name="project_id" defaultValue={event?.project_id}><option value="">No project</option>{projects.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</SelectInput></div><div><FieldLabel label="Task" htmlFor="event-task" /><SelectInput id="event-task" name="task_id" defaultValue={event?.task_id}><option value="">No task</option>{tasks.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</SelectInput></div></div><div><FieldLabel label="Notes" htmlFor="event-notes" /><TextArea id="event-notes" name="notes" defaultValue={event?.notes} rows={3} /></div></div>; }
export function NewEventForm({ clients, projects, tasks }: { clients: Option[]; projects: Option[]; tasks: Option[] }) { const [state, action] = useActionState(createCalendarEventAction, initialState); return <Shell title="Add meeting or work block"><form action={action} className="space-y-5"><EventFields clients={clients} projects={projects} tasks={tasks} /><div className="flex flex-wrap items-center gap-4"><SubmitButton>Create calendar item</SubmitButton><FormMessage {...state} /></div></form></Shell>; }
export function EditEventForm({ clients, projects, tasks, event }: { clients: Option[]; projects: Option[]; tasks: Option[]; event: Event }) { const [state, action] = useActionState(updateCalendarEventAction, initialState); return <form action={action} className="space-y-4"><input type="hidden" name="id" value={event.id} /><EventFields clients={clients} projects={projects} tasks={tasks} event={event} /><div className="flex flex-wrap items-center gap-4"><SubmitButton>Save calendar item</SubmitButton><FormMessage {...state} /></div></form>; }
export function DeleteEventForm({ id }: { id: string }) { const [state, action] = useActionState(deleteCalendarEventAction, initialState); return <form action={action} className="flex flex-wrap gap-3"><input type="hidden" name="id" value={id} /><SubmitButton pendingLabel="Removing…" className="bg-background px-0 py-0 text-xs font-normal text-muted-foreground ring-0">Remove</SubmitButton><FormMessage {...state} /></form>; }
export function ScheduleTaskForm({ taskId, date }: { taskId: string; date: string | null }) { const [state, action] = useActionState(rescheduleTaskAction, initialState); return <form action={action} className="flex flex-wrap items-center gap-2"><input type="hidden" name="task_id" value={taskId} /><TextInput id={`schedule-${taskId}`} name="scheduled_date" type="date" defaultValue={date ?? ""} /><SubmitButton pendingLabel="Saving…" className="px-3 py-1.5 text-xs">Schedule</SubmitButton><FormMessage {...state} /></form>; }
