#!/usr/bin/env bash
# Builds the paste-able scripts for the Supabase SQL editor:
#   supabase/scripts/apply/NN_<name>.sql   one file per pending migration (0014 → latest), each its own transaction
#   supabase/scripts/apply/05_owner.sql    sets the owner explicitly (run right after 0014)
#   supabase/scripts/pending-migrations.sql  everything in one file (single transaction)
#
#   OWNER_EMAIL=you@example.com supabase/scripts/build-pending-migrations.sh
#
# Dollar-quote tags are rewritten from $$ to unique named tags ($az1$, $az2$, …). Some editors and
# copy/paste paths mangle a bare "$$", which surfaces as "42P13: no function body specified".
# Only run the generated files against a database that already has 0001–0013.
set -euo pipefail
cd "$(dirname "$0")/.."
OWNER_EMAIL="${OWNER_EMAIL:-drummerforger@gmail.com}"
OUT=scripts/pending-migrations.sql
DIR=scripts/apply
rm -rf "$DIR"; mkdir -p "$DIR"

retag() {
  # Replace each pair of bare $$ delimiters with a unique named tag. Fails if the count is odd.
  python3 - "$1" "$2" <<'PY'
import re, sys
src, tag = open(sys.argv[1]).read(), sys.argv[2]
parts = src.split("$$")
if len(parts) % 2 == 0:
    sys.exit("odd number of $$ delimiters in " + sys.argv[1])
out = [parts[0]]
for i in range(1, len(parts)):
    n = (i + 1) // 2
    out.append(f"${tag}{n}$" + parts[i])
sys.stdout.write("".join(out))
PY
}

owner_sql() {
  cat <<SQL
-- Makes '$OWNER_EMAIL' the Agency Zero owner. Aborts if no such sign-in exists yet.
begin;
do \$own\$
declare v_id uuid;
begin
  select id into v_id from auth.users where lower(email) = lower('$OWNER_EMAIL') limit 1;
  if v_id is null then
    raise exception 'No auth user with email $OWNER_EMAIL — sign in once (or create the user) first, then re-run';
  end if;
  insert into public.app_owner (id, user_id) values (1, v_id)
  on conflict (id) do update set user_id = excluded.user_id;
end
\$own\$;
commit;
SQL
}

i=0
{
  echo "-- GENERATED by supabase/scripts/build-pending-migrations.sh — do not edit by hand."
  echo "-- Everything from 0014 to the latest migration, owner '$OWNER_EMAIL', in ONE transaction (all or nothing)."
  echo "-- Prefer the one-file-per-migration scripts in supabase/scripts/apply/ — easier to run and to diagnose."
  echo "begin;"
  echo
} > "$OUT"
for f in migrations/00{14,15,16,17,18,19}_*.sql migrations/002[0-9]_*.sql; do
  [ -e "$f" ] || continue
  num=$(basename "$f" | cut -c1-4)
  base=$(basename "$f" .sql)
  {
    echo "-- Migration $base — run in the Supabase SQL editor. Wrapped in a transaction: all or nothing."
    echo "begin;"
    retag "$f" "m${num}x"
    echo
    echo "commit;"
  } > "$DIR/$base.sql"
  { echo "-- ▶ $f"; retag "$f" "m${num}x"; echo; } >> "$OUT"
  if [ "$num" = "0014" ]; then
    owner_sql > "$DIR/0014b_set_owner.sql"
    { owner_sql | sed '/^begin;$/d;/^commit;$/d'; echo; } >> "$OUT"
  fi
done
echo "commit;" >> "$OUT"
echo "wrote $(ls $DIR | wc -l) files in supabase/$DIR and supabase/$OUT for owner $OWNER_EMAIL"
