#!/usr/bin/env bash
# Builds supabase/scripts/pending-migrations.sql: migrations 0014 → latest in one
# paste-able file for the Supabase SQL editor, in a single transaction, with the
# owner row explicitly set to the given email right after 0014.
#
#   OWNER_EMAIL=you@example.com supabase/scripts/build-pending-migrations.sh
#
# Only run the generated file against a database that already has 0001–0013.
# (Never run migrations you have already applied; check the header comment.)
set -euo pipefail
cd "$(dirname "$0")/.."
OWNER_EMAIL="${OWNER_EMAIL:-drummerforger@gmail.com}"
OUT=scripts/pending-migrations.sql
{
  echo "-- GENERATED by supabase/scripts/build-pending-migrations.sh — do not edit by hand."
  echo "-- Applies migrations 0014 → $(ls migrations | tail -1 | cut -c1-4) in ONE transaction (all or nothing)."
  echo "-- Prerequisite: 0001–0013 already applied. If any of 0014+ was applied before, stop and ask."
  echo "-- Owner: '$OWNER_EMAIL' becomes the Agency Zero owner (the migration aborts if that user does not exist)."
  echo "begin;"
  echo
  for f in migrations/0014_*.sql; do echo "-- ▶ $f"; cat "$f"; echo; done
  cat <<SQL
-- ▶ make '$OWNER_EMAIL' the owner explicitly (do not rely on "oldest profile")
do \$\$
declare v_id uuid;
begin
  select id into v_id from auth.users where lower(email) = lower('$OWNER_EMAIL') limit 1;
  if v_id is null then
    raise exception 'No auth user with email $OWNER_EMAIL — sign in once (or create the user) first, then re-run';
  end if;
  insert into public.app_owner (id, user_id) values (1, v_id)
  on conflict (id) do update set user_id = excluded.user_id;
end
\$\$;

SQL
  for f in migrations/00{15,16,17,18,19}_*.sql migrations/002[0-9]_*.sql; do
    [ -e "$f" ] || continue
    echo "-- ▶ $f"; cat "$f"; echo
  done
  echo "commit;"
} > "$OUT"
echo "wrote supabase/$OUT ($(wc -l < "$OUT") lines) for owner $OWNER_EMAIL"
