-- GENERATED by supabase/scripts/build-pending-migrations.sh — do not edit by hand.
-- Everything from 0014 to the latest migration, owner 'drummerforger@gmail.com', in ONE transaction (all or nothing).
-- Prefer the one-file-per-migration scripts in supabase/scripts/apply/ — easier to run and to diagnose.
begin;

-- ▶ migrations/0014_owner_only_rls.sql
-- ═══════════════════════════════════════════════════════════════════════════
-- Agency Zero — 0014: owner-only RLS (audit finding S1 / BUGS B-001)
--
-- Until now every policy was `auth.uid() is not null`, i.e. ANY authenticated
-- user was "the owner". That is only safe while Supabase public sign-ups are
-- disabled. This migration makes the database itself enforce single-owner
-- access, so an accidentally enabled sign-up (or an invited user) can no
-- longer read or write business data.
--
-- Design
--   * `public.app_owner` — singleton row holding the owner's auth user id.
--     RLS is enabled with NO policies: only the SECURITY DEFINER function
--     below can read it.
--   * Seeded from the oldest existing profile (the owner created first). On a
--     brand-new database the first user created becomes the owner
--     (`handle_new_user()` is updated accordingly).
--   * `public.is_owner()` — true when auth.uid() is the owner.
--   * Every policy that used the old "authenticated" predicate is rewritten to
--     `is_owner()`, including Storage policies for `client-files`.
--   * `profiles` keeps `id = auth.uid()` (a user can only see their own row).
--
-- !! BEFORE APPLYING TO PRODUCTION !!
--   Confirm the owner's profile is the OLDEST row in public.profiles:
--     select id, full_name, created_at from public.profiles order by created_at;
--   If not, fix the row after applying:
--     update public.app_owner set user_id = '<owner auth.users id>' where id = 1;
--   Applying this migration does not lock the owner out as long as that holds.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── owner registry ─────────────────────────────────────────────────────────
create table if not exists public.app_owner (
  id integer primary key default 1 check (id = 1),
  user_id uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

comment on table public.app_owner is
  'Singleton: the one auth user allowed to access business data. Read only via public.is_owner().';

alter table public.app_owner enable row level security;
-- Intentionally no policies: not readable or writable through the API.
revoke all on public.app_owner from anon, authenticated;

insert into public.app_owner (id, user_id)
select 1, p.id
from public.profiles p
order by p.created_at, p.id
limit 1
on conflict (id) do nothing;

create or replace function public.is_owner()
returns boolean
language sql
stable
security definer
set search_path = public
as $m0014x1$
  select exists (
    select 1 from public.app_owner o where o.user_id = (select auth.uid())
  );
$m0014x1$;

revoke execute on function public.is_owner() from public;
grant execute on function public.is_owner() to anon, authenticated;

-- First user on an empty database becomes the owner; later sign-ups get a
-- profile row (harmless: RLS hides everything) but never ownership.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $m0014x2$
begin
  insert into public.profiles (id, full_name)
  values (
    new.id,
    coalesce(
      nullif(new.raw_user_meta_data ->> 'full_name', ''),
      split_part(coalesce(new.email, 'owner'), '@', 1)
    )
  );

  insert into public.settings (id) values (1) on conflict (id) do nothing;
  insert into public.app_owner (id, user_id) values (1, new.id) on conflict (id) do nothing;

  return new;
end;
$m0014x2$;

revoke execute on function public.handle_new_user() from public, anon, authenticated;

-- ── rewrite every "any authenticated user" policy ─────────────────────────
do $m0014x3$
declare
  pol record;
  using_clause text;
  check_clause text;
  rewritten integer := 0;
begin
  for pol in
    select schemaname, tablename, policyname, cmd
    from pg_policies
    where schemaname = 'public'
      and (coalesce(qual, '') ~* 'auth\.uid\(\).*is not null'
        or coalesce(with_check, '') ~* 'auth\.uid\(\).*is not null')
  loop
    using_clause := case when pol.cmd in ('ALL', 'SELECT', 'UPDATE', 'DELETE') then ' using (public.is_owner())' else '' end;
    check_clause := case when pol.cmd in ('ALL', 'INSERT', 'UPDATE') then ' with check (public.is_owner())' else '' end;
    execute format('alter policy %I on %I.%I%s%s',
      pol.policyname, pol.schemaname, pol.tablename, using_clause, check_clause);
    rewritten := rewritten + 1;
  end loop;
  raise notice '0014: rewrote % policies to is_owner()', rewritten;
end
$m0014x3$;

-- ── Storage: client-files bucket ───────────────────────────────────────────
drop policy if exists "Owner reads client files" on storage.objects;
drop policy if exists "Owner uploads client files" on storage.objects;
drop policy if exists "Owner updates client files" on storage.objects;
drop policy if exists "Owner deletes client files" on storage.objects;

create policy "Owner reads client files"
  on storage.objects for select to authenticated
  using (bucket_id = 'client-files' and public.is_owner());
create policy "Owner uploads client files"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'client-files' and public.is_owner());
create policy "Owner updates client files"
  on storage.objects for update to authenticated
  using (bucket_id = 'client-files' and public.is_owner())
  with check (bucket_id = 'client-files' and public.is_owner());
create policy "Owner deletes client files"
  on storage.objects for delete to authenticated
  using (bucket_id = 'client-files' and public.is_owner());

-- ── SECURITY DEFINER RPCs that previously only checked auth.uid() ──────────
-- These bypass RLS, so they need the owner check themselves.
create or replace function public.convert_quote_to_project(p_quote_id uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $m0014x4$
declare q public.quotes%rowtype; project_uuid uuid;
begin
  if not public.is_owner() then raise exception 'Authentication required'; end if;
  select * into q from public.quotes where id = p_quote_id for update;
  if not found then raise exception 'Quote not found'; end if;
  if q.status <> 'accepted' then raise exception 'Only accepted quotes can become projects'; end if;
  if q.converted_project_id is not null then return q.converted_project_id; end if;
  insert into public.projects (client_id, name, description, status, value_cents, currency, progress)
  values (q.client_id, q.title, 'Created from accepted quote ' || q.number, 'planning', q.total_cents, q.currency, 0)
  returning id into project_uuid;
  update public.quotes set converted_project_id = project_uuid where id = q.id;
  return project_uuid;
end;
$m0014x4$;

create or replace function public.refresh_invoice_statuses()
returns void
language plpgsql
security definer
set search_path = public
as $m0014x5$
begin
  if not public.is_owner() then raise exception 'Authentication required'; end if;
  update public.invoices
  set status = 'overdue'::invoice_status
  where status in ('sent', 'partially_paid') and due_on < current_date and paid_cents < total_cents;
end;
$m0014x5$;

-- ── safety net: fail the migration if any open policy remains ──────────────
do $m0014x6$
declare leftover integer;
begin
  select count(*) into leftover
  from pg_policies
  where schemaname in ('public', 'storage')
    and 'authenticated' = any (roles)
    and (coalesce(qual, '') ~* 'auth\.uid\(\).*is not null'
      or coalesce(with_check, '') ~* 'auth\.uid\(\).*is not null');
  if leftover > 0 then
    raise exception '0014: % policies still use the any-authenticated predicate', leftover;
  end if;
end
$m0014x6$;

-- Makes 'drummerforger@gmail.com' the Agency Zero owner. Aborts if no such sign-in exists yet.
do $own$
declare v_id uuid;
begin
  select id into v_id from auth.users where lower(email) = lower('drummerforger@gmail.com') limit 1;
  if v_id is null then
    raise exception 'No auth user with email drummerforger@gmail.com — sign in once (or create the user) first, then re-run';
  end if;
  insert into public.app_owner (id, user_id) values (1, v_id)
  on conflict (id) do update set user_id = excluded.user_id;
end
$own$;

-- ▶ migrations/0015_transactional_saves_and_invoice_protection.sql
-- ═══════════════════════════════════════════════════════════════════════════
-- Agency Zero — 0015: atomic quote/invoice saves + financial record protection
-- (audit BUGS B-004, B-005)
--
--   A. `save_quote()` / `save_invoice()` — header + line items in ONE
--      transaction. Previously the app deleted the lines, then inserted them,
--      then (for updates) had already rewritten the header; any failure left a
--      quote or invoice with missing or stale lines.
--      Both are SECURITY INVOKER, so RLS (owner-only, 0014) and the
--      accepted-quote immutability triggers (0008) still apply.
--   B. Invoices that are not drafts can no longer be deleted (void them), and
--      an invoice with payments can never be deleted: payments → invoice is
--      now ON DELETE RESTRICT instead of CASCADE.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── A. save_quote ──────────────────────────────────────────────────────────
create or replace function public.save_quote(
  p_id uuid,
  p_header jsonb,
  p_lines jsonb,
  p_token text default null,
  p_token_hash text default null
)
returns uuid
language plpgsql
security invoker
set search_path = public
as $m0015x1$
declare
  h public.quotes%rowtype;
  v_id uuid;
begin
  if jsonb_typeof(p_lines) is distinct from 'array' then
    raise exception 'Line items must be a JSON array';
  end if;

  h := jsonb_populate_record(null::public.quotes, p_header);

  if p_id is null then
    if p_token is null or p_token_hash is null then
      raise exception 'A public token is required for new quotes';
    end if;
    insert into public.quotes (
      client_id, number, title, notes, status, issued_on, valid_until, currency,
      subtotal_cents, discount_cents, tax_rate, tax_cents, total_cents,
      public_token, public_token_hash
    ) values (
      h.client_id, h.number, h.title, h.notes, h.status, h.issued_on, h.valid_until, h.currency,
      h.subtotal_cents, h.discount_cents, h.tax_rate, h.tax_cents, h.total_cents,
      p_token, p_token_hash
    ) returning id into v_id;
  else
    update public.quotes q set
      client_id = h.client_id, number = h.number, title = h.title, notes = h.notes,
      status = h.status, issued_on = h.issued_on, valid_until = h.valid_until,
      currency = h.currency, subtotal_cents = h.subtotal_cents,
      discount_cents = h.discount_cents, tax_rate = h.tax_rate,
      tax_cents = h.tax_cents, total_cents = h.total_cents
    where q.id = p_id
    returning q.id into v_id;
    if v_id is null then raise exception 'Quote not found'; end if;
  end if;

  delete from public.quote_line_items where quote_id = v_id;
  insert into public.quote_line_items (
    quote_id, sort_order, service_id, description, details, qty, unit_amount_cents,
    is_recurring, billing_period, amount_cents, selection, option_group
  )
  select v_id, coalesce(l.sort_order, 0), l.service_id, l.description, l.details,
         coalesce(l.qty, 1), coalesce(l.unit_amount_cents, 0),
         coalesce(l.is_recurring, false), l.billing_period, coalesce(l.amount_cents, 0),
         coalesce(l.selection, 'fixed'), l.option_group
  from jsonb_populate_recordset(null::public.quote_line_items, p_lines) l;

  return v_id;
end;
$m0015x1$;

-- ── A. save_invoice ────────────────────────────────────────────────────────
create or replace function public.save_invoice(
  p_id uuid,
  p_header jsonb,
  p_lines jsonb
)
returns uuid
language plpgsql
security invoker
set search_path = public
as $m0015x2$
declare
  h public.invoices%rowtype;
  v_id uuid;
  v_paid integer;
begin
  if jsonb_typeof(p_lines) is distinct from 'array' then
    raise exception 'Line items must be a JSON array';
  end if;

  h := jsonb_populate_record(null::public.invoices, p_header);

  if p_id is null then
    insert into public.invoices (
      client_id, project_id, quote_id, contract_id, number, title, status,
      issued_on, due_on, currency, subtotal_cents, discount_cents, tax_cents,
      total_cents, deposit_cents, paid_cents, balance_cents
    ) values (
      h.client_id, h.project_id, h.quote_id, h.contract_id, h.number, h.title, h.status,
      h.issued_on, h.due_on, h.currency, h.subtotal_cents, h.discount_cents, h.tax_cents,
      h.total_cents, h.deposit_cents, 0, h.total_cents
    ) returning id into v_id;
  else
    select i.paid_cents into v_paid from public.invoices i where i.id = p_id for update;
    if not found then raise exception 'Invoice not found'; end if;
    if h.total_cents < v_paid then
      raise exception 'Invoice total cannot be lower than payments already recorded';
    end if;
    update public.invoices i set
      client_id = h.client_id, project_id = h.project_id, quote_id = h.quote_id,
      contract_id = h.contract_id, number = h.number, title = h.title, status = h.status,
      issued_on = h.issued_on, due_on = h.due_on, currency = h.currency,
      subtotal_cents = h.subtotal_cents, discount_cents = h.discount_cents,
      tax_cents = h.tax_cents, total_cents = h.total_cents,
      deposit_cents = h.deposit_cents, balance_cents = h.total_cents - v_paid
    where i.id = p_id
    returning i.id into v_id;
  end if;

  delete from public.invoice_line_items where invoice_id = v_id;
  insert into public.invoice_line_items (
    invoice_id, sort_order, description, qty, unit_amount_cents, amount_cents
  )
  select v_id, coalesce(l.sort_order, 0), l.description, coalesce(l.qty, 1),
         coalesce(l.unit_amount_cents, 0), coalesce(l.amount_cents, 0)
  from jsonb_populate_recordset(null::public.invoice_line_items, p_lines) l;

  return v_id;
end;
$m0015x2$;

revoke execute on function public.save_quote(uuid, jsonb, jsonb, text, text) from public, anon;
revoke execute on function public.save_invoice(uuid, jsonb, jsonb) from public, anon;
grant execute on function public.save_quote(uuid, jsonb, jsonb, text, text) to authenticated;
grant execute on function public.save_invoice(uuid, jsonb, jsonb) to authenticated;

-- ── B. financial record protection ─────────────────────────────────────────
do $m0015x3$
declare fk text;
begin
  select c.conname into fk
  from pg_constraint c
  where c.conrelid = 'public.payments'::regclass
    and c.contype = 'f'
    and c.confrelid = 'public.invoices'::regclass;
  if fk is not null then
    execute format('alter table public.payments drop constraint %I', fk);
  end if;
  alter table public.payments
    add constraint payments_invoice_id_fkey
    foreign key (invoice_id) references public.invoices (id) on delete restrict;
end
$m0015x3$;

create or replace function public.protect_issued_invoice()
returns trigger
language plpgsql
set search_path = public
as $m0015x4$
begin
  if old.status <> 'draft' then
    raise exception 'Only draft invoices can be deleted. Void the invoice instead.';
  end if;
  return old;
end;
$m0015x4$;

drop trigger if exists invoices_protect_issued on public.invoices;
create trigger invoices_protect_issued
  before delete on public.invoices
  for each row execute function public.protect_issued_invoice();

revoke execute on function public.protect_issued_invoice() from public, anon, authenticated;

-- ▶ migrations/0016_payment_ledger_and_signature_evidence.sql
-- ═══════════════════════════════════════════════════════════════════════════
-- Agency Zero — 0016: permanent payment ledger + e-signature evidence
-- (audit BUGS B-011, finding S3)
--
--   A. Payments are never deleted or edited. A mistaken payment is VOIDED
--      (`voided_at` + mandatory `void_reason`); voided rows stay in the ledger,
--      are excluded from invoice totals, and a void cannot be undone (record a
--      new payment instead). Enforced by a trigger, so it holds for every
--      client, not just this app.
--   B. Invoice status is re-derived correctly when a payment is voided
--      (e.g. `paid` → `partially_paid`/`sent`).
--   C. The client and project workspace read models also return `voided_at`
--      for each payment (patched in place so 0012/0013 stay untouched).
--   D. Contract signatures now capture evidence: IP address, user agent, the
--      exact consent statement shown, and a SHA-256 of the signed body.
--      Signed contracts remain immutable, including the new columns.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── A. payment ledger ──────────────────────────────────────────────────────
alter table public.payments
  add column if not exists voided_at timestamptz,
  add column if not exists void_reason text;

alter table public.payments drop constraint if exists payments_void_reason_check;
alter table public.payments
  add constraint payments_void_reason_check
  check (voided_at is null or length(trim(coalesce(void_reason, ''))) > 0);

create or replace function public.protect_payment_ledger()
returns trigger
language plpgsql
set search_path = public
as $m0016x1$
begin
  if tg_op = 'DELETE' then
    raise exception 'Payments are permanent records and cannot be deleted. Void the payment instead.';
  end if;
  if new.invoice_id is distinct from old.invoice_id
    or new.amount_cents is distinct from old.amount_cents
    or new.paid_on is distinct from old.paid_on
    or new.method is distinct from old.method
    or new.kind is distinct from old.kind
    or new.reference is distinct from old.reference
    or new.created_at is distinct from old.created_at
  then
    raise exception 'Payment details cannot be edited. Void the payment and record a new one.';
  end if;
  if old.voided_at is not null
    and (new.voided_at is distinct from old.voided_at or new.void_reason is distinct from old.void_reason)
  then
    raise exception 'A voided payment cannot be changed or restored. Record a new payment instead.';
  end if;
  return new;
end;
$m0016x1$;

drop trigger if exists payments_protect_ledger on public.payments;
create trigger payments_protect_ledger
  before update or delete on public.payments
  for each row execute function public.protect_payment_ledger();

revoke execute on function public.protect_payment_ledger() from public, anon, authenticated;

-- ── B. recalculation ignores voided payments and un-sticks invoice status ──
create or replace function public.recalculate_invoice_payment()
returns trigger
language plpgsql
security definer
set search_path = public
as $m0016x2$
declare
  invoice_uuid uuid;
  paid integer;
  total integer;
  due date;
  current_status invoice_status;
begin
  invoice_uuid := coalesce(new.invoice_id, old.invoice_id);
  select i.total_cents, i.due_on, i.status into total, due, current_status
  from public.invoices i where i.id = invoice_uuid;
  select coalesce(sum(p.amount_cents), 0)::integer into paid
  from public.payments p where p.invoice_id = invoice_uuid and p.voided_at is null;
  update public.invoices
  set paid_cents = paid,
      balance_cents = total - paid,
      status = case
        when current_status = 'void' then 'void'::invoice_status
        when total > 0 and paid >= total then 'paid'::invoice_status
        when paid > 0 then 'partially_paid'::invoice_status
        when current_status in ('paid', 'partially_paid') then 'sent'::invoice_status
        when due < current_date and current_status in ('sent', 'overdue') then 'overdue'::invoice_status
        else current_status
      end
  where id = invoice_uuid;
  return coalesce(new, old);
end;
$m0016x2$;

revoke execute on function public.recalculate_invoice_payment() from public, anon, authenticated;

-- ── C. read models expose voided_at ────────────────────────────────────────
do $m0016x3$
declare
  fn text;
  def text;
  patched text;
begin
  foreach fn in array array['public.get_client_workspace(uuid)', 'public.get_project_workspace(uuid)']
  loop
    def := pg_get_functiondef(fn::regprocedure);
    patched := replace(def, '''method'', pm.method, ''kind'', pm.kind', '''method'', pm.method, ''kind'', pm.kind, ''voided_at'', pm.voided_at');
    if patched = def then
      raise exception '0016: could not patch % (payments projection changed)', fn;
    end if;
    execute patched;
  end loop;
end
$m0016x3$;

-- ── D. signature evidence ──────────────────────────────────────────────────
alter table public.contracts
  add column if not exists signer_ip text,
  add column if not exists signer_user_agent text,
  add column if not exists consent_text text,
  add column if not exists signed_body_sha256 text;

create or replace function public.protect_signed_contract()
returns trigger
language plpgsql
set search_path = public
as $m0016x4$
begin
  if old.status = 'signed'::public.contract_status then
    if tg_op = 'DELETE' then
      raise exception 'Signed contracts cannot be deleted; they are a permanent record.';
    end if;
    if new.status is distinct from old.status
      or new.client_id is distinct from old.client_id
      or new.title is distinct from old.title
      or new.body is distinct from old.body
      or new.template_id is distinct from old.template_id
      or new.version is distinct from old.version
      or new.viewed_at is distinct from old.viewed_at
      or new.signed_at is distinct from old.signed_at
      or new.signer_name is distinct from old.signer_name
      or new.signed_snapshot is distinct from old.signed_snapshot
      or new.signed_file_path is distinct from old.signed_file_path
      or new.signer_ip is distinct from old.signer_ip
      or new.signer_user_agent is distinct from old.signer_user_agent
      or new.consent_text is distinct from old.consent_text
      or new.signed_body_sha256 is distinct from old.signed_body_sha256
    then
      raise exception 'Signed contracts are immutable.';
    end if;
  end if;
  return coalesce(new, old);
end;
$m0016x4$;

-- Replace the 2-argument signer with one that records evidence.
drop function if exists public.sign_public_contract(text, text);

create or replace function public.sign_public_contract(
  p_token_hash text,
  p_signer_name text,
  p_signer_ip text default null,
  p_signer_user_agent text default null,
  p_consent_text text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $m0016x5$
declare result jsonb;
begin
  if length(trim(p_signer_name)) < 2 or length(trim(p_signer_name)) > 160 then
    raise exception 'Enter a valid signer name';
  end if;
  update public.contracts
  set status = 'signed'::contract_status,
      signer_name = trim(p_signer_name),
      signed_at = now(),
      signed_snapshot = body,
      signed_body_sha256 = encode(sha256(convert_to(body, 'UTF8')), 'hex'),
      signer_ip = left(nullif(trim(p_signer_ip), ''), 64),
      signer_user_agent = left(nullif(trim(p_signer_user_agent), ''), 400),
      consent_text = left(nullif(trim(p_consent_text), ''), 1000),
      viewed_at = coalesce(viewed_at, now())
  where public_token_hash = p_token_hash
    and (token_expires_at is null or token_expires_at > now())
    and status = 'sent';
  if not found then raise exception 'This contract is no longer available for signing'; end if;
  select jsonb_build_object('status', status, 'signed_at', signed_at, 'signer_name', signer_name)
    into result from public.contracts where public_token_hash = p_token_hash;
  return result;
end;
$m0016x5$;

revoke execute on function public.sign_public_contract(text, text, text, text, text) from public;
grant execute on function public.sign_public_contract(text, text, text, text, text) to anon, authenticated;

-- ▶ migrations/0017_invoice_summary.sql
-- ═══════════════════════════════════════════════════════════════════════════
-- Agency Zero — 0017: invoice KPIs as a server-side aggregate
--
-- The invoices page computed its KPIs by summing the rows it had loaded. Once
-- the list is bounded (audit B-008) that would understate revenue, and it also
-- counted void/draft invoices as "outstanding". This read model computes the
-- totals over ALL invoices in Postgres:
--   revenue     = money actually received (sum of non-voided payments, which is
--                 invoices.paid_cents, on every invoice including void ones)
--   outstanding = unpaid balance on issued, non-void invoices (draft excluded)
--   overdue     = issued, non-void, balance > 0 and past due
-- Security invoker: RLS (owner-only) applies.
-- ═══════════════════════════════════════════════════════════════════════════
create or replace function public.get_invoice_summary(p_today date default null)
returns jsonb
language sql
stable
security invoker
set search_path = public
as $m0017x1$
  select jsonb_build_object(
    'invoice_count', count(*),
    'revenue_cents', coalesce(sum(i.paid_cents), 0),
    'outstanding_cents', coalesce(sum(i.balance_cents) filter (where i.status not in ('draft', 'void')), 0),
    'overdue_count', count(*) filter (
      where i.status not in ('draft', 'void', 'paid')
        and i.balance_cents > 0
        and i.due_on < coalesce(p_today, current_date)
    ),
    'currency', coalesce((select i2.currency from public.invoices i2 order by i2.created_at desc limit 1), 'USD')
  )
  from public.invoices i;
$m0017x1$;

revoke execute on function public.get_invoice_summary(date) from public, anon;
grant execute on function public.get_invoice_summary(date) to authenticated;

-- ▶ migrations/0018_team_access_and_revenue_summary.sql
-- ═══════════════════════════════════════════════════════════════════════════
-- Agency Zero — 0018: authorised team access + real revenue read model
--
--   A. `public.app_team` — users the owner explicitly authorises to use the
--      CRM. `public.is_owner()` (the single check behind every RLS policy and
--      the /app layout) now returns true for the owner OR a team member, so no
--      policy needs rewriting. The table has RLS enabled with no policies:
--      nobody can add themselves through the API. Grant access with SQL, e.g.
--        insert into public.app_team (user_id) select id from auth.users where email = 'person@example.com';
--      and revoke with `delete from public.app_team where user_id = '…';`.
--   B. `public.get_revenue_summary(p_today)` — money actually RECEIVED:
--        total_revenue_cents       = sum of every non-voided payment (one-time
--                                    jobs, deposits, installments, recurring)
--        revenue_this_month_cents  = same, paid_on within p_today's month
--        outstanding_cents         = unpaid balance on issued, non-void invoices
--      Quoted values, drafts and unpaid invoices never count as revenue.
--      Security invoker: RLS applies. `mixed_currency` is true when payments
--      exist in more than one currency (amounts are then not directly addable).
-- ═══════════════════════════════════════════════════════════════════════════

-- ── A. team access ─────────────────────────────────────────────────────────
create table if not exists public.app_team (
  user_id uuid primary key references auth.users (id) on delete cascade,
  role text not null default 'member' check (role in ('member')),
  granted_at timestamptz not null default now()
);

comment on table public.app_team is
  'Users explicitly authorised (by the owner, via SQL) to use the CRM. Not readable or writable through the API.';

alter table public.app_team enable row level security;
revoke all on public.app_team from anon, authenticated;

create or replace function public.is_owner()
returns boolean
language sql
stable
security definer
set search_path = public
as $m0018x1$
  select exists (select 1 from public.app_owner o where o.user_id = (select auth.uid()))
      or exists (select 1 from public.app_team t where t.user_id = (select auth.uid()));
$m0018x1$;

revoke execute on function public.is_owner() from public;
grant execute on function public.is_owner() to anon, authenticated;

-- ── B. revenue summary ─────────────────────────────────────────────────────
create or replace function public.get_revenue_summary(p_today date default null)
returns jsonb
language sql
stable
security invoker
set search_path = public
as $m0018x2$
  with bounds as (
    select date_trunc('month', coalesce(p_today, current_date))::date as month_start,
           (date_trunc('month', coalesce(p_today, current_date)) + interval '1 month')::date as month_end
  ),
  received as (
    select
      coalesce(sum(p.amount_cents), 0)::bigint as total_cents,
      coalesce(sum(p.amount_cents) filter (
        where p.paid_on >= b.month_start and p.paid_on < b.month_end
      ), 0)::bigint as month_cents,
      count(distinct i.currency) as currencies
    from public.payments p
    join public.invoices i on i.id = p.invoice_id
    cross join bounds b
    where p.voided_at is null
  ),
  owed as (
    select coalesce(sum(i.balance_cents), 0)::bigint as outstanding_cents
    from public.invoices i
    where i.status not in ('draft', 'void')
  )
  select jsonb_build_object(
    'total_revenue_cents', r.total_cents,
    'revenue_this_month_cents', r.month_cents,
    'outstanding_cents', o.outstanding_cents,
    'mixed_currency', r.currencies > 1,
    'currency', coalesce(
      (select i2.currency from public.invoices i2 order by i2.created_at desc limit 1),
      (select s.default_currency from public.settings s where s.id = 1),
      'USD')
  )
  from received r cross join owed o;
$m0018x2$;

revoke execute on function public.get_revenue_summary(date) from public, anon;
grant execute on function public.get_revenue_summary(date) to authenticated;

-- ▶ migrations/0019_website_leads.sql
-- ═══════════════════════════════════════════════════════════════════════════
-- Agency Zero — 0019: website leads (public contact form → CRM)
--
-- The public site's project-inquiry form lands here. Design:
--   * `public.leads` is owner-only (RLS via is_owner()): nobody but the owner /
--     authorised team can read, edit or delete leads through the API.
--   * Anonymous visitors can ONLY call `public.submit_lead(...)` — a narrow
--     SECURITY DEFINER function that validates every field, whitelists the
--     service list, and rate-limits by a hashed submitter fingerprint and by
--     email (no raw IP is stored). It returns only the new id.
--   * `public.convert_lead_to_client(lead_id)` (security invoker, owner only)
--     turns a lead into a client + primary contact in one transaction.
-- ═══════════════════════════════════════════════════════════════════════════

create type public.lead_status as enum ('new', 'contacted', 'converted', 'dismissed');

create table public.leads (
  id uuid primary key default gen_random_uuid(),
  name text not null check (length(trim(name)) between 1 and 160),
  business text check (business is null or length(business) <= 200),
  email text not null check (length(email) <= 254 and position('@' in email) > 1),
  phone text check (phone is null or length(phone) <= 40),
  services text[] not null default '{}',
  budget text check (budget is null or length(budget) <= 60),
  details text check (details is null or length(details) <= 4000),
  source text not null default 'website',
  status public.lead_status not null default 'new',
  client_id uuid references public.clients (id) on delete set null,
  submitter_hash text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.leads is
  'Inbound project inquiries from the public website. Owner-only; written by submit_lead().';

create index leads_status_created_idx on public.leads (status, created_at desc);
create index leads_submitter_idx on public.leads (submitter_hash, created_at desc);
create index leads_email_idx on public.leads (lower(email), created_at desc);

alter table public.leads enable row level security;

create policy "Owner manages leads"
  on public.leads for all to authenticated
  using (public.is_owner()) with check (public.is_owner());

create trigger leads_set_updated_at
  before update on public.leads
  for each row execute function public.set_updated_at();

-- ── public submission ──────────────────────────────────────────────────────
create or replace function public.submit_lead(
  p_name text,
  p_business text,
  p_email text,
  p_phone text,
  p_services text[],
  p_budget text,
  p_details text,
  p_submitter_hash text default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $m0019x1$
declare
  v_id uuid;
  v_name text := trim(coalesce(p_name, ''));
  v_email text := lower(trim(coalesce(p_email, '')));
  v_allowed text[] := array['software', 'websites', 'seo', 'meta-ads', 'social', 'content', 'not-sure'];
  v_services text[] := coalesce(p_services, '{}');
begin
  if length(v_name) < 1 or length(v_name) > 160 then raise exception 'Please enter your name'; end if;
  if length(v_email) > 254 or v_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then
    raise exception 'Please enter a valid email address';
  end if;
  if length(coalesce(p_details, '')) > 4000 then raise exception 'Project details are too long'; end if;
  if cardinality(v_services) > 8 or not (v_services <@ v_allowed) then raise exception 'Invalid service selection'; end if;

  -- Rate limits: protect the inbox and the database from floods.
  if (select count(*) from public.leads l where lower(l.email) = v_email and l.created_at > now() - interval '1 hour') >= 3 then
    raise exception 'Too many requests, please try again later';
  end if;
  if p_submitter_hash is not null
     and (select count(*) from public.leads l where l.submitter_hash = p_submitter_hash and l.created_at > now() - interval '1 hour') >= 5 then
    raise exception 'Too many requests, please try again later';
  end if;
  if (select count(*) from public.leads l where l.created_at > now() - interval '1 hour') >= 200 then
    raise exception 'Too many requests, please try again later';
  end if;

  insert into public.leads (name, business, email, phone, services, budget, details, submitter_hash)
  values (
    v_name,
    nullif(left(trim(coalesce(p_business, '')), 200), ''),
    v_email,
    nullif(left(trim(coalesce(p_phone, '')), 40), ''),
    v_services,
    nullif(left(trim(coalesce(p_budget, '')), 60), ''),
    nullif(trim(coalesce(p_details, '')), ''),
    left(p_submitter_hash, 128)
  )
  returning id into v_id;
  return v_id;
end;
$m0019x1$;

revoke execute on function public.submit_lead(text, text, text, text, text[], text, text, text) from public;
grant execute on function public.submit_lead(text, text, text, text, text[], text, text, text) to anon, authenticated;

-- ── lead → client ──────────────────────────────────────────────────────────
create or replace function public.convert_lead_to_client(p_lead_id uuid)
returns uuid
language plpgsql
security invoker
set search_path = public
as $m0019x2$
declare
  l public.leads%rowtype;
  v_client uuid;
begin
  select * into l from public.leads where id = p_lead_id for update;
  if not found then raise exception 'Lead not found'; end if;
  if l.client_id is not null then return l.client_id; end if;

  insert into public.clients (name, status, company, email, phone, source, notes_summary)
  values (
    coalesce(nullif(l.business, ''), l.name),
    'lead',
    nullif(l.business, ''),
    l.email,
    l.phone,
    'website',
    nullif(concat_ws(E'\n', 'Interested in: ' || nullif(array_to_string(l.services, ', '), ''), 'Budget: ' || l.budget, l.details), '')
  )
  returning id into v_client;

  insert into public.contacts (client_id, name, email, phone, is_primary)
  values (v_client, l.name, l.email, l.phone, true);

  update public.leads set status = 'converted', client_id = v_client where id = l.id;
  return v_client;
end;
$m0019x2$;

revoke execute on function public.convert_lead_to_client(uuid) from public, anon;
grant execute on function public.convert_lead_to_client(uuid) to authenticated;

-- ▶ migrations/0020_record_client_payment.sql
-- ═══════════════════════════════════════════════════════════════════════════
-- Agency Zero — 0020: record a payment received in one step
--
-- Total Revenue is the sum of payments received. Until now a payment could only be
-- added to an existing invoice, so a one-time fee ("built a website, charged $2,500")
-- never reached the dashboard unless an invoice was created first. This function
-- creates a PAID invoice (one line item) and its payment in a single transaction,
-- so the fee shows up in Total Revenue immediately and stays auditable in the
-- invoice/payment ledger. Security INVOKER: RLS (is_owner()) applies.
-- ═══════════════════════════════════════════════════════════════════════════

create or replace function public.record_client_payment(
  p_client_id uuid,
  p_description text,
  p_amount_cents integer,
  p_paid_on date default null,
  p_method text default 'other',
  p_project_id uuid default null,
  p_reference text default null
)
returns uuid
language plpgsql
security invoker
set search_path = public
as $m0020x1$
declare
  v_paid_on date := coalesce(p_paid_on, current_date);
  v_currency text;
  v_year text := to_char(v_paid_on, 'YYYY');
  v_next integer;
  v_number text;
  v_invoice uuid;
  v_description text := trim(coalesce(p_description, ''));
begin
  if p_amount_cents is null or p_amount_cents <= 0 then
    raise exception 'Enter an amount greater than zero';
  end if;
  if length(v_description) = 0 or length(v_description) > 200 then
    raise exception 'Describe what the payment was for (up to 200 characters)';
  end if;
  if p_method not in ('bank_transfer', 'cash', 'card', 'other', 'stripe') then
    raise exception 'Invalid payment method';
  end if;
  if not exists (select 1 from public.clients c where c.id = p_client_id and c.deleted_at is null) then
    raise exception 'Client not found';
  end if;
  if p_project_id is not null
     and not exists (select 1 from public.projects p where p.id = p_project_id and p.client_id = p_client_id) then
    raise exception 'That project does not belong to this client';
  end if;

  select coalesce((select s.default_currency from public.settings s where s.id = 1), 'USD') into v_currency;

  -- Serialise number allocation so two quick saves cannot pick the same number.
  perform pg_advisory_xact_lock(hashtext('invoice-number'));
  select coalesce(max((regexp_match(i.number, '^INV-' || v_year || '-(\d+)$'))[1]::integer), 0) + 1
    into v_next
  from public.invoices i
  where i.number ~ ('^INV-' || v_year || '-\d+$');
  v_number := 'INV-' || v_year || '-' || lpad(v_next::text, 4, '0');

  insert into public.invoices (
    client_id, project_id, number, title, status, issued_on, due_on, currency,
    subtotal_cents, discount_cents, tax_cents, total_cents, deposit_cents, paid_cents, balance_cents
  ) values (
    p_client_id, p_project_id, v_number, v_description, 'sent', v_paid_on, v_paid_on, v_currency,
    p_amount_cents, 0, 0, p_amount_cents, 0, 0, p_amount_cents
  ) returning id into v_invoice;

  insert into public.invoice_line_items (invoice_id, sort_order, description, qty, unit_amount_cents, amount_cents)
  values (v_invoice, 0, v_description, 1, p_amount_cents, p_amount_cents);

  -- The payment trigger recalculates paid/balance and flips the invoice to 'paid'.
  insert into public.payments (invoice_id, amount_cents, paid_on, method, kind, reference)
  values (v_invoice, p_amount_cents, v_paid_on, p_method::public.payment_method, 'full', nullif(trim(coalesce(p_reference, '')), ''));

  return v_invoice;
end;
$m0020x1$;

revoke execute on function public.record_client_payment(uuid, text, integer, date, text, uuid, text) from public, anon;
grant execute on function public.record_client_payment(uuid, text, integer, date, text, uuid, text) to authenticated;

-- ▶ migrations/0021_marketing_and_social.sql
-- ═══════════════════════════════════════════════════════════════════════════
-- Agency Zero — 0021: marketing campaigns and social content
--
-- Two small owner-only tables so the Marketing and Social sections of the CRM
-- are real working tools (before the ad-platform integrations exist):
--   * marketing_campaigns — paid/organic campaigns per client, with budget,
--     spend and results entered by hand.
--   * social_posts — a content calendar per client and platform.
-- Both follow the repo rules: RLS via is_owner(), integer minor units for money.
-- ═══════════════════════════════════════════════════════════════════════════

create type public.campaign_channel as enum ('meta_ads', 'google_ads', 'seo', 'email', 'other');
create type public.campaign_status as enum ('planned', 'active', 'paused', 'completed');

create table public.marketing_campaigns (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references public.clients (id) on delete restrict,
  name text not null check (length(trim(name)) between 1 and 160),
  channel public.campaign_channel not null default 'meta_ads',
  status public.campaign_status not null default 'planned',
  objective text check (objective is null or length(objective) <= 500),
  starts_on date,
  ends_on date,
  budget_cents integer check (budget_cents is null or budget_cents >= 0),
  spend_cents integer not null default 0 check (spend_cents >= 0),
  leads_count integer not null default 0 check (leads_count >= 0),
  results_note text check (results_note is null or length(results_note) <= 2000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_on is null or starts_on is null or ends_on >= starts_on)
);
create index marketing_campaigns_client_idx on public.marketing_campaigns (client_id, created_at desc);
create index marketing_campaigns_status_idx on public.marketing_campaigns (status, starts_on);

create type public.social_platform as enum ('instagram', 'facebook', 'tiktok', 'linkedin', 'youtube', 'x', 'other');
create type public.social_format as enum ('post', 'reel', 'story', 'carousel', 'video');
create type public.social_status as enum ('idea', 'drafting', 'scheduled', 'posted');

create table public.social_posts (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references public.clients (id) on delete restrict,
  platform public.social_platform not null default 'instagram',
  format public.social_format not null default 'post',
  status public.social_status not null default 'idea',
  caption text check (caption is null or length(caption) <= 4000),
  scheduled_for timestamptz,
  post_url text check (post_url is null or length(post_url) <= 500),
  notes text check (notes is null or length(notes) <= 2000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index social_posts_client_idx on public.social_posts (client_id, scheduled_for);
create index social_posts_status_idx on public.social_posts (status, scheduled_for);

alter table public.marketing_campaigns enable row level security;
alter table public.social_posts enable row level security;

create policy "Owner manages campaigns"
  on public.marketing_campaigns for all to authenticated
  using (public.is_owner()) with check (public.is_owner());
create policy "Owner manages social posts"
  on public.social_posts for all to authenticated
  using (public.is_owner()) with check (public.is_owner());

create trigger marketing_campaigns_set_updated_at
  before update on public.marketing_campaigns
  for each row execute function public.set_updated_at();
create trigger social_posts_set_updated_at
  before update on public.social_posts
  for each row execute function public.set_updated_at();

grant select, insert, update, delete on public.marketing_campaigns to authenticated;
grant select, insert, update, delete on public.social_posts to authenticated;

-- ▶ migrations/0022_venmo_payment_method.sql
-- ═══════════════════════════════════════════════════════════════════════════
-- Agency Zero — 0022: Venmo as a payment method
--
-- Adds 'venmo' to public.payment_method and re-creates record_client_payment (from
-- 0020) so it accepts it. Safe to run whether or not 0020 was applied: this file
-- contains the full, current function, so running it alone is enough.
-- ═══════════════════════════════════════════════════════════════════════════

alter type public.payment_method add value if not exists 'venmo';

create or replace function public.record_client_payment(
  p_client_id uuid,
  p_description text,
  p_amount_cents integer,
  p_paid_on date default null,
  p_method text default 'other',
  p_project_id uuid default null,
  p_reference text default null
)
returns uuid
language plpgsql
security invoker
set search_path = public
as $m0022x1$
declare
  v_paid_on date := coalesce(p_paid_on, current_date);
  v_currency text;
  v_year text := to_char(v_paid_on, 'YYYY');
  v_next integer;
  v_number text;
  v_invoice uuid;
  v_description text := trim(coalesce(p_description, ''));
begin
  if p_amount_cents is null or p_amount_cents <= 0 then
    raise exception 'Enter an amount greater than zero';
  end if;
  if length(v_description) = 0 or length(v_description) > 200 then
    raise exception 'Describe what the payment was for (up to 200 characters)';
  end if;
  if p_method not in ('bank_transfer', 'cash', 'card', 'other', 'stripe', 'venmo') then
    raise exception 'Invalid payment method';
  end if;
  if not exists (select 1 from public.clients c where c.id = p_client_id and c.deleted_at is null) then
    raise exception 'Client not found';
  end if;
  if p_project_id is not null
     and not exists (select 1 from public.projects p where p.id = p_project_id and p.client_id = p_client_id) then
    raise exception 'That project does not belong to this client';
  end if;

  select coalesce((select s.default_currency from public.settings s where s.id = 1), 'USD') into v_currency;

  -- Serialise number allocation so two quick saves cannot pick the same number.
  perform pg_advisory_xact_lock(hashtext('invoice-number'));
  select coalesce(max((regexp_match(i.number, '^INV-' || v_year || '-(\d+)$'))[1]::integer), 0) + 1
    into v_next
  from public.invoices i
  where i.number ~ ('^INV-' || v_year || '-\d+$');
  v_number := 'INV-' || v_year || '-' || lpad(v_next::text, 4, '0');

  insert into public.invoices (
    client_id, project_id, number, title, status, issued_on, due_on, currency,
    subtotal_cents, discount_cents, tax_cents, total_cents, deposit_cents, paid_cents, balance_cents
  ) values (
    p_client_id, p_project_id, v_number, v_description, 'sent', v_paid_on, v_paid_on, v_currency,
    p_amount_cents, 0, 0, p_amount_cents, 0, 0, p_amount_cents
  ) returning id into v_invoice;

  insert into public.invoice_line_items (invoice_id, sort_order, description, qty, unit_amount_cents, amount_cents)
  values (v_invoice, 0, v_description, 1, p_amount_cents, p_amount_cents);

  -- The payment trigger recalculates paid/balance and flips the invoice to 'paid'.
  insert into public.payments (invoice_id, amount_cents, paid_on, method, kind, reference)
  values (v_invoice, p_amount_cents, v_paid_on, p_method::public.payment_method, 'full', nullif(trim(coalesce(p_reference, '')), ''));

  return v_invoice;
end;
$m0022x1$;

revoke execute on function public.record_client_payment(uuid, text, integer, date, text, uuid, text) from public, anon;
grant execute on function public.record_client_payment(uuid, text, integer, date, text, uuid, text) to authenticated;

-- ▶ migrations/0023_work_items.sql
-- ═══════════════════════════════════════════════════════════════════════════
-- Agency Zero — 0023: unified work items (tasks, bugs, feature requests)
--
-- One table, three kinds. Bugs and feature requests are `tasks` rows with a
-- `kind`, so they inherit status, priority, due date, time tracking, milestones
-- and calendar scheduling for free. Bug-only fields: `severity`. Both new kinds:
-- `requester_contact_id` (who asked), `source` (where it came from) and
-- `resolution` (what was done / why declined). Existing rows become kind 'task'.
--
-- Status vocabulary is shared (todo / in_progress / blocked_* / done / cancelled);
-- the UI labels it per kind (bug: Open → Fixed / Won't fix; feature: Requested →
-- Shipped / Declined).
--
-- `get_project_work_items()` is a separate read model (rather than patching
-- get_project_workspace) so a production database that has drifted from the repo
-- cannot make this migration fail.
-- ═══════════════════════════════════════════════════════════════════════════

create type public.work_item_kind as enum ('task', 'bug', 'feature_request');
create type public.bug_severity as enum ('low', 'medium', 'high', 'critical');

alter table public.tasks
  add column kind public.work_item_kind not null default 'task',
  add column severity public.bug_severity,
  add column requester_contact_id uuid references public.contacts (id) on delete set null,
  add column source text not null default 'internal',
  add column resolution text;

alter table public.tasks
  add constraint tasks_source_check check (source in ('internal', 'client', 'website', 'message', 'other')),
  add constraint tasks_resolution_length check (resolution is null or length(resolution) <= 2000),
  add constraint tasks_severity_only_for_bugs check (severity is null or kind = 'bug');

create index tasks_kind_status_idx on public.tasks (kind, status);
create index tasks_requester_idx on public.tasks (requester_contact_id) where requester_contact_id is not null;

comment on column public.tasks.kind is 'task | bug | feature_request (unified work items).';

create or replace function public.get_project_work_items(p_project_id uuid)
returns jsonb
language sql
stable
security invoker
set search_path = public
as $m0023x1$
  select jsonb_build_object(
    'items', coalesce((
      select jsonb_agg(row_to_json(w)::jsonb order by w.open_rank, w.severity_rank, w.due_date nulls last, w.created_at desc)
      from (
        select
          t.id, t.kind, t.title, t.description, t.status, t.priority, t.severity,
          t.due_date, t.source, t.resolution, t.requester_contact_id,
          c.name as requester_name, t.milestone_id, t.created_at, t.updated_at,
          t.scheduled_date, t.estimated_minutes, t.actual_minutes, t.parent_task_id, t.depends_on_task_id, t.recurrence_rule,
          '/tasks/' || t.id::text as href,
          case when t.status in ('done', 'cancelled') then 1 else 0 end as open_rank,
          case t.severity when 'critical' then 0 when 'high' then 1 when 'medium' then 2 when 'low' then 3 else 4 end as severity_rank
        from public.tasks t
        left join public.contacts c on c.id = t.requester_contact_id
        where t.project_id = p_project_id and t.kind <> 'task'
        order by open_rank, severity_rank, t.due_date nulls last, t.created_at desc
        limit 300
      ) w
    ), '[]'::jsonb),
    'open_bugs', (select count(*) from public.tasks t where t.project_id = p_project_id and t.kind = 'bug' and t.status not in ('done', 'cancelled')),
    'open_critical', (select count(*) from public.tasks t where t.project_id = p_project_id and t.kind = 'bug' and t.severity = 'critical' and t.status not in ('done', 'cancelled')),
    'open_feature_requests', (select count(*) from public.tasks t where t.project_id = p_project_id and t.kind = 'feature_request' and t.status not in ('done', 'cancelled')),
    'contacts', coalesce((
      select jsonb_agg(jsonb_build_object('id', c.id, 'name', c.name, 'role', c.role) order by c.is_primary desc, c.name)
      from public.contacts c
      join public.projects p on p.client_id = c.client_id
      where p.id = p_project_id
    ), '[]'::jsonb)
  );
$m0023x1$;

revoke execute on function public.get_project_work_items(uuid) from public, anon;
grant execute on function public.get_project_work_items(uuid) to authenticated;

-- ▶ migrations/0024_content_shoots.sql
-- ═══════════════════════════════════════════════════════════════════════════
-- Agency Zero — 0024: recurring content shoot schedules
--
-- A client on a content plan gets a shoot every week / every other week / the
-- Nth weekday of the month. A *schedule* is the recurring rule; a *shoot* is one
-- dated occurrence (with its own status, location, notes and checklist).
--
--   shoot_schedules — the rule (frequency, weekday, start time, duration,
--                     location, checklist template, active, start/end dates).
--   shoots          — occurrences. Unique per (schedule, date), so generating
--                     twice never creates duplicates.
--   generate_shoots()      — materialises occurrences up to a horizon
--                            (default 90 days, max 366). Idempotent. Explicit:
--                            nothing is generated on page render.
--   get_shoots_overview()  — one read model for the Shoots page and client tab.
--
-- Times are wall-clock (`shoot_date` + `start_time`, no time zone): a 10:00
-- shoot is 10:00 where the shoot is. Dates are plain `date`s.
-- ═══════════════════════════════════════════════════════════════════════════

create type public.shoot_frequency as enum ('weekly', 'biweekly', 'monthly');
create type public.shoot_status as enum ('planned', 'confirmed', 'shot', 'rescheduled', 'cancelled');

create table public.shoot_schedules (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references public.clients (id) on delete restrict,
  project_id uuid references public.projects (id) on delete set null,
  title text not null check (length(trim(title)) between 1 and 160),
  frequency public.shoot_frequency not null default 'monthly',
  weekday smallint not null check (weekday between 0 and 6),            -- 0 = Sunday
  week_of_month smallint check (week_of_month between 1 and 5),         -- 5 = last (monthly only)
  start_time time,
  duration_minutes integer not null default 120 check (duration_minutes between 15 and 1440),
  location text check (location is null or length(location) <= 300),
  checklist jsonb not null default '[]'::jsonb check (jsonb_typeof(checklist) = 'array'),
  notes text check (notes is null or length(notes) <= 2000),
  starts_on date not null default current_date,
  ends_on date,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (frequency <> 'monthly' or week_of_month is not null),
  check (ends_on is null or ends_on >= starts_on)
);
create index shoot_schedules_client_idx on public.shoot_schedules (client_id, active);

create table public.shoots (
  id uuid primary key default gen_random_uuid(),
  schedule_id uuid references public.shoot_schedules (id) on delete set null,
  client_id uuid not null references public.clients (id) on delete restrict,
  project_id uuid references public.projects (id) on delete set null,
  title text not null check (length(trim(title)) between 1 and 160),
  shoot_date date not null,
  start_time time,
  duration_minutes integer not null default 120 check (duration_minutes between 15 and 1440),
  location text check (location is null or length(location) <= 300),
  status public.shoot_status not null default 'planned',
  checklist jsonb not null default '[]'::jsonb check (jsonb_typeof(checklist) = 'array'),
  notes text check (notes is null or length(notes) <= 2000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index shoots_schedule_date_uidx on public.shoots (schedule_id, shoot_date) where schedule_id is not null;
create index shoots_date_idx on public.shoots (shoot_date, status);
create index shoots_client_idx on public.shoots (client_id, shoot_date);

alter table public.shoot_schedules enable row level security;
alter table public.shoots enable row level security;

create policy "Owner manages shoot schedules"
  on public.shoot_schedules for all to authenticated
  using (public.is_owner()) with check (public.is_owner());
create policy "Owner manages shoots"
  on public.shoots for all to authenticated
  using (public.is_owner()) with check (public.is_owner());

create trigger shoot_schedules_set_updated_at
  before update on public.shoot_schedules
  for each row execute function public.set_updated_at();
create trigger shoots_set_updated_at
  before update on public.shoots
  for each row execute function public.set_updated_at();

grant select, insert, update, delete on public.shoot_schedules to authenticated;
grant select, insert, update, delete on public.shoots to authenticated;

-- ── generation ─────────────────────────────────────────────────────────────
-- Creates the schedule's occurrences from p_from (default today, never before the schedule starts)
-- through p_until (default +90 days; capped at +366 days and at ends_on). Returns how many were created.
-- p_reset first removes this schedule's FUTURE shoots that are still 'planned' (use after changing the rule);
-- confirmed / shot / cancelled shoots are never touched.
create or replace function public.generate_shoots(
  p_schedule_id uuid,
  p_until date default null,
  p_reset boolean default false,
  p_from date default null
)
returns integer
language plpgsql
security invoker
set search_path = public
as $m0024x1$
declare
  s public.shoot_schedules%rowtype;
  v_today date := coalesce(p_from, current_date);
  v_from date;
  v_until date;
  v_anchor date;
  v_day date;
  v_count integer := 0;
  v_rows integer;
  v_checklist jsonb;
begin
  select * into s from public.shoot_schedules where id = p_schedule_id;
  if not found then
    raise exception 'Schedule not found';
  end if;

  if p_reset then
    delete from public.shoots
    where schedule_id = s.id and status = 'planned' and shoot_date >= v_today;
  end if;
  if not s.active then
    return 0;
  end if;

  v_from := greatest(s.starts_on, v_today);
  v_until := least(coalesce(p_until, v_today + 90), v_today + 366, coalesce(s.ends_on, date '9999-12-31'));
  if v_until < v_from then
    return 0;
  end if;

  -- First date on/after starts_on that falls on the chosen weekday: the anchor for "every other week".
  v_anchor := s.starts_on + ((s.weekday - extract(dow from s.starts_on)::int + 7) % 7);

  select coalesce(jsonb_agg(jsonb_build_object('text', item, 'done', false)), '[]'::jsonb)
    into v_checklist
  from jsonb_array_elements_text(s.checklist) as item;

  for v_day in select g::date from generate_series(v_from, v_until, interval '1 day') as g loop
    continue when extract(dow from v_day)::int <> s.weekday;
    if s.frequency = 'biweekly' and ((v_day - v_anchor) / 7) % 2 <> 0 then
      continue;
    end if;
    if s.frequency = 'monthly' then
      if s.week_of_month = 5 then
        continue when extract(month from v_day + 7) = extract(month from v_day);   -- not the last one of the month
      else
        continue when ceil(extract(day from v_day) / 7.0)::int <> s.week_of_month;
      end if;
    end if;

    insert into public.shoots (schedule_id, client_id, project_id, title, shoot_date, start_time, duration_minutes, location, checklist, notes)
    values (s.id, s.client_id, s.project_id, s.title, v_day, s.start_time, s.duration_minutes, s.location, v_checklist, s.notes)
    on conflict (schedule_id, shoot_date) where schedule_id is not null do nothing;
    get diagnostics v_rows = row_count;
    v_count := v_count + v_rows;
  end loop;

  return v_count;
end;
$m0024x1$;

revoke execute on function public.generate_shoots(uuid, date, boolean, date) from public, anon;
grant execute on function public.generate_shoots(uuid, date, boolean, date) to authenticated;

-- ── atomic save ────────────────────────────────────────────────────────────
-- Create (p_id null) or update a schedule and (re)generate its upcoming shoots in ONE transaction.
-- On update, future shoots that are still 'planned' are rebuilt from the new rule; confirmed / shot / cancelled are kept.
-- Pausing (active = false) therefore also clears the upcoming planned shoots. Returns {id, created, shoots_created}.
create or replace function public.save_shoot_schedule(p_id uuid, p_data jsonb)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $m0024x2$
declare
  v_id uuid := p_id;
  v_created integer;
begin
  if p_id is null then
    insert into public.shoot_schedules (
      client_id, project_id, title, frequency, weekday, week_of_month, start_time, duration_minutes,
      location, checklist, notes, starts_on, ends_on, active
    ) values (
      (p_data ->> 'client_id')::uuid,
      nullif(p_data ->> 'project_id', '')::uuid,
      p_data ->> 'title',
      (p_data ->> 'frequency')::public.shoot_frequency,
      (p_data ->> 'weekday')::smallint,
      nullif(p_data ->> 'week_of_month', '')::smallint,
      nullif(p_data ->> 'start_time', '')::time,
      coalesce(nullif(p_data ->> 'duration_minutes', '')::integer, 120),
      nullif(p_data ->> 'location', ''),
      coalesce(p_data -> 'checklist', '[]'::jsonb),
      nullif(p_data ->> 'notes', ''),
      coalesce(nullif(p_data ->> 'starts_on', '')::date, current_date),
      nullif(p_data ->> 'ends_on', '')::date,
      coalesce((p_data ->> 'active')::boolean, true)
    ) returning id into v_id;
  else
    update public.shoot_schedules set
      client_id = (p_data ->> 'client_id')::uuid,
      project_id = nullif(p_data ->> 'project_id', '')::uuid,
      title = p_data ->> 'title',
      frequency = (p_data ->> 'frequency')::public.shoot_frequency,
      weekday = (p_data ->> 'weekday')::smallint,
      week_of_month = nullif(p_data ->> 'week_of_month', '')::smallint,
      start_time = nullif(p_data ->> 'start_time', '')::time,
      duration_minutes = coalesce(nullif(p_data ->> 'duration_minutes', '')::integer, 120),
      location = nullif(p_data ->> 'location', ''),
      checklist = coalesce(p_data -> 'checklist', '[]'::jsonb),
      notes = nullif(p_data ->> 'notes', ''),
      starts_on = coalesce(nullif(p_data ->> 'starts_on', '')::date, starts_on),
      ends_on = nullif(p_data ->> 'ends_on', '')::date,
      active = coalesce((p_data ->> 'active')::boolean, active)
    where id = p_id;
    if not found then
      raise exception 'Schedule not found';
    end if;
  end if;

  v_created := public.generate_shoots(v_id, null, p_id is not null);
  return jsonb_build_object('id', v_id, 'created', p_id is null, 'shoots_created', v_created);
end;
$m0024x2$;

revoke execute on function public.save_shoot_schedule(uuid, jsonb) from public, anon;
grant execute on function public.save_shoot_schedule(uuid, jsonb) to authenticated;

-- ── read model ─────────────────────────────────────────────────────────────
create or replace function public.get_shoots_overview(p_client_id uuid default null, p_today date default null)
returns jsonb
language sql
stable
security invoker
set search_path = public
as $m0024x3$
  with params as (select coalesce(p_today, current_date) as today)
  select jsonb_build_object(
    'schedules', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', s.id, 'client_id', s.client_id, 'client_name', c.name, 'project_id', s.project_id,
        'title', s.title, 'frequency', s.frequency, 'weekday', s.weekday, 'week_of_month', s.week_of_month,
        'start_time', s.start_time, 'duration_minutes', s.duration_minutes, 'location', s.location,
        'checklist', s.checklist, 'notes', s.notes, 'starts_on', s.starts_on, 'ends_on', s.ends_on, 'active', s.active,
        'next_shoot', (select min(h.shoot_date) from public.shoots h, params p
                        where h.schedule_id = s.id and h.shoot_date >= p.today and h.status in ('planned', 'confirmed')),
        'generated_through', (select max(h.shoot_date) from public.shoots h where h.schedule_id = s.id)
      ) order by s.active desc, lower(c.name), s.title)
      from public.shoot_schedules s
      join public.clients c on c.id = s.client_id
      where p_client_id is null or s.client_id = p_client_id
    ), '[]'::jsonb),
    'upcoming', coalesce((
      select jsonb_agg(row_to_json(u)::jsonb order by u.shoot_date, u.start_time nulls last)
      from (
        select h.id, h.schedule_id, h.client_id, c.name as client_name, h.project_id, h.title, h.shoot_date, h.start_time,
               h.duration_minutes, h.location, h.status, h.checklist, h.notes
        from public.shoots h
        join public.clients c on c.id = h.client_id, params p
        where h.shoot_date >= p.today and h.status in ('planned', 'confirmed')
          and (p_client_id is null or h.client_id = p_client_id)
        order by h.shoot_date, h.start_time nulls last
        limit 150
      ) u
    ), '[]'::jsonb),
    'recent', coalesce((
      select jsonb_agg(row_to_json(r)::jsonb order by r.shoot_date desc)
      from (
        select h.id, h.client_id, c.name as client_name, h.title, h.shoot_date, h.start_time, h.location, h.status, h.notes
        from public.shoots h
        join public.clients c on c.id = h.client_id, params p
        where (h.shoot_date < p.today or h.status in ('shot', 'cancelled', 'rescheduled'))
          and (p_client_id is null or h.client_id = p_client_id)
        order by h.shoot_date desc
        limit 30
      ) r
    ), '[]'::jsonb),
    'client_options', coalesce((
      select jsonb_agg(jsonb_build_object('id', c.id, 'name', c.name) order by lower(c.name))
      from public.clients c where c.deleted_at is null and (p_client_id is null or c.id = p_client_id)
    ), '[]'::jsonb),
    'project_options', coalesce((
      select jsonb_agg(jsonb_build_object('id', pr.id, 'name', pr.name, 'client_id', pr.client_id) order by lower(pr.name))
      from public.projects pr where pr.deleted_at is null and (p_client_id is null or pr.client_id = p_client_id)
    ), '[]'::jsonb)
  );
$m0024x3$;

revoke execute on function public.get_shoots_overview(uuid, date) from public, anon;
grant execute on function public.get_shoots_overview(uuid, date) to authenticated;

-- ▶ migrations/0025_project_phases_and_templates.sql
-- ═══════════════════════════════════════════════════════════════════════════
-- Agency Zero — 0025: project phases and templates per service type
--
-- Phases are the ordered stages of a project (Discovery → Design → Build → QA → Launch). Tasks can belong to a
-- phase. A template is a reusable list of phases with starter tasks per service type; applying one to a project
-- creates its phases and tasks in one transaction.
--
--   project_phases     — ordered stages per project (upcoming / active / done)
--   tasks.phase_id     — optional link from a task to its phase
--   project_templates  — owner-editable templates (phases jsonb), seeded with one per service
--   apply_project_template() — atomic: phases + tasks, with due dates counted from a start date
--   move_project_phase()     — swap a phase with its neighbour (reorder)
--   get_project_phases()     — one read model for the Phases tab
-- ═══════════════════════════════════════════════════════════════════════════

create type public.phase_status as enum ('upcoming', 'active', 'done');

create table public.project_phases (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects (id) on delete cascade,
  name text not null check (length(trim(name)) between 1 and 120),
  sort_order integer not null default 0,
  status public.phase_status not null default 'upcoming',
  starts_on date,
  due_on date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (due_on is null or starts_on is null or due_on >= starts_on)
);
create index project_phases_project_idx on public.project_phases (project_id, sort_order);

alter table public.tasks add column phase_id uuid references public.project_phases (id) on delete set null;
create index tasks_phase_idx on public.tasks (phase_id) where phase_id is not null;

create table public.project_templates (
  id uuid primary key default gen_random_uuid(),
  name text not null unique check (length(trim(name)) between 1 and 120),
  service_kind text not null default 'other' check (service_kind in ('software', 'websites', 'seo', 'meta_ads', 'social', 'content', 'other')),
  description text check (description is null or length(description) <= 500),
  phases jsonb not null default '[]'::jsonb check (jsonb_typeof(phases) = 'array'),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.project_phases enable row level security;
alter table public.project_templates enable row level security;

create policy "Owner manages project phases"
  on public.project_phases for all to authenticated
  using (public.is_owner()) with check (public.is_owner());
create policy "Owner manages project templates"
  on public.project_templates for all to authenticated
  using (public.is_owner()) with check (public.is_owner());

create trigger project_phases_set_updated_at
  before update on public.project_phases
  for each row execute function public.set_updated_at();
create trigger project_templates_set_updated_at
  before update on public.project_templates
  for each row execute function public.set_updated_at();

grant select, insert, update, delete on public.project_phases to authenticated;
grant select, insert, update, delete on public.project_templates to authenticated;

-- Template format: [{"name": "Discovery", "tasks": [{"title": "Kickoff call", "priority": "high", "day": 0}]}]
-- `day` = days after the start date the task is due (optional).
create or replace function public.apply_project_template(p_project_id uuid, p_template_id uuid, p_start date default null)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $m0025x1$
declare
  v_project public.projects%rowtype;
  v_template public.project_templates%rowtype;
  v_phase jsonb;
  v_task jsonb;
  v_phase_id uuid;
  v_order integer := 0;
  v_phases integer := 0;
  v_tasks integer := 0;
  v_priority text;
begin
  select * into v_project from public.projects where id = p_project_id and deleted_at is null;
  if not found then
    raise exception 'Project not found';
  end if;
  select * into v_template from public.project_templates where id = p_template_id and active;
  if not found then
    raise exception 'Template not found';
  end if;
  if exists (select 1 from public.project_phases where project_id = p_project_id) then
    raise exception 'This project already has phases';
  end if;
  if jsonb_array_length(v_template.phases) = 0 then
    raise exception 'That template has no phases';
  end if;

  for v_phase in select value from jsonb_array_elements(v_template.phases) loop
    insert into public.project_phases (project_id, name, sort_order, status)
    values (p_project_id, left(trim(v_phase ->> 'name'), 120), v_order, case when v_order = 0 then 'active'::public.phase_status else 'upcoming'::public.phase_status end)
    returning id into v_phase_id;
    v_order := v_order + 1;
    v_phases := v_phases + 1;

    for v_task in select value from jsonb_array_elements(coalesce(v_phase -> 'tasks', '[]'::jsonb)) loop
      v_priority := coalesce(v_task ->> 'priority', 'medium');
      if v_priority not in ('low', 'medium', 'high', 'urgent') then
        v_priority := 'medium';
      end if;
      insert into public.tasks (project_id, client_id, phase_id, title, priority, due_date)
      values (
        p_project_id, v_project.client_id, v_phase_id, left(trim(v_task ->> 'title'), 240), v_priority::public.task_priority,
        case when p_start is not null and (v_task ->> 'day') ~ '^\d{1,4}$' then p_start + (v_task ->> 'day')::integer else null end
      );
      v_tasks := v_tasks + 1;
    end loop;
  end loop;

  return jsonb_build_object('phases', v_phases, 'tasks', v_tasks);
end;
$m0025x1$;

revoke execute on function public.apply_project_template(uuid, uuid, date) from public, anon;
grant execute on function public.apply_project_template(uuid, uuid, date) to authenticated;

-- Move a phase up (-1) or down (+1) by swapping sort_order with its neighbour.
create or replace function public.move_project_phase(p_phase_id uuid, p_direction integer)
returns void
language plpgsql
security invoker
set search_path = public
as $m0025x2$
declare
  v_phase public.project_phases%rowtype;
  v_other public.project_phases%rowtype;
begin
  select * into v_phase from public.project_phases where id = p_phase_id;
  if not found then
    raise exception 'Phase not found';
  end if;
  if p_direction < 0 then
    select * into v_other from public.project_phases
    where project_id = v_phase.project_id and (sort_order, id::text) < (v_phase.sort_order, v_phase.id::text)
    order by sort_order desc, id::text desc limit 1;
  else
    select * into v_other from public.project_phases
    where project_id = v_phase.project_id and (sort_order, id::text) > (v_phase.sort_order, v_phase.id::text)
    order by sort_order, id::text limit 1;
  end if;
  if not found then
    return;
  end if;
  if v_other.sort_order = v_phase.sort_order then
    -- equal sort values: nudge so the swap is visible
    update public.project_phases set sort_order = v_phase.sort_order + (case when p_direction < 0 then -1 else 1 end) where id = v_phase.id;
  else
    update public.project_phases set sort_order = v_other.sort_order where id = v_phase.id;
    update public.project_phases set sort_order = v_phase.sort_order where id = v_other.id;
  end if;
end;
$m0025x2$;

revoke execute on function public.move_project_phase(uuid, integer) from public, anon;
grant execute on function public.move_project_phase(uuid, integer) to authenticated;

create or replace function public.get_project_phases(p_project_id uuid)
returns jsonb
language sql
stable
security invoker
set search_path = public
as $m0025x3$
  select jsonb_build_object(
    'phases', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', ph.id, 'name', ph.name, 'sort_order', ph.sort_order, 'status', ph.status,
        'starts_on', ph.starts_on, 'due_on', ph.due_on,
        'total_tasks', (select count(*) from public.tasks t where t.phase_id = ph.id),
        'open_tasks', (select count(*) from public.tasks t where t.phase_id = ph.id and t.status not in ('done', 'cancelled'))
      ) order by ph.sort_order, ph.created_at)
      from public.project_phases ph where ph.project_id = p_project_id
    ), '[]'::jsonb),
    'task_phases', coalesce((
      select jsonb_agg(jsonb_build_object('id', t.id, 'phase_id', t.phase_id))
      from public.tasks t where t.project_id = p_project_id and t.phase_id is not null
    ), '[]'::jsonb),
    'templates', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', pt.id, 'name', pt.name, 'service_kind', pt.service_kind, 'description', pt.description,
        'phase_count', jsonb_array_length(pt.phases),
        'task_count', (select coalesce(sum(jsonb_array_length(coalesce(p -> 'tasks', '[]'::jsonb))), 0) from jsonb_array_elements(pt.phases) p)
      ) order by pt.service_kind, pt.name)
      from public.project_templates pt where pt.active
    ), '[]'::jsonb)
  );
$m0025x3$;

revoke execute on function public.get_project_phases(uuid) from public, anon;
grant execute on function public.get_project_phases(uuid) to authenticated;

-- Default templates (editable in the app).
insert into public.project_templates (name, service_kind, description, phases) values
  ('Software build', 'software', 'Custom software, CRM or internal tool: discovery to launch.', '[{"name": "Discovery", "tasks": [{"title": "Kickoff call and goals", "priority": "high", "day": 0}, {"title": "Map the current workflow", "priority": "medium", "day": 3}, {"title": "Agree scope and success measures", "priority": "high", "day": 7}]}, {"name": "Design", "tasks": [{"title": "Data model and key screens", "priority": "medium", "day": 14}, {"title": "Client review of designs", "priority": "high", "day": 18}]}, {"name": "Build", "tasks": [{"title": "Core build: first usable slice", "priority": "medium", "day": 35}, {"title": "Integrations (payments, email, calendar)", "priority": "medium", "day": 45}, {"title": "Automations", "priority": "medium", "day": 55}]}, {"name": "QA & fixes", "tasks": [{"title": "Test every workflow end to end", "priority": "high", "day": 62}, {"title": "Fix bugs from testing", "priority": "medium", "day": 66}, {"title": "Security and permissions check", "priority": "medium", "day": 68}]}, {"name": "Launch & handover", "tasks": [{"title": "Migrate data", "priority": "medium", "day": 72}, {"title": "Train the team", "priority": "medium", "day": 75}, {"title": "Go live and monitor", "priority": "high", "day": 77}, {"title": "Handover notes and support plan", "priority": "medium", "day": 80}]}]'::jsonb),
  ('Website build', 'websites', 'A custom website from first call to launch.', '[{"name": "Discovery & content", "tasks": [{"title": "Kickoff call and goals", "priority": "high", "day": 0}, {"title": "Collect logo, brand and photos", "priority": "medium", "day": 5}, {"title": "Write or approve page copy", "priority": "medium", "day": 10}]}, {"name": "Design", "tasks": [{"title": "Homepage design", "priority": "high", "day": 14}, {"title": "Inner page designs", "priority": "medium", "day": 21}, {"title": "Client design approval", "priority": "high", "day": 25}]}, {"name": "Build", "tasks": [{"title": "Build pages", "priority": "medium", "day": 35}, {"title": "Forms, tracking and SEO basics", "priority": "medium", "day": 40}, {"title": "Mobile and speed checks", "priority": "medium", "day": 43}]}, {"name": "Review & revisions", "tasks": [{"title": "Client review round", "priority": "high", "day": 47}, {"title": "Revisions", "priority": "medium", "day": 52}]}, {"name": "Launch", "tasks": [{"title": "Domain, hosting and redirects", "priority": "medium", "day": 55}, {"title": "Go live", "priority": "high", "day": 57}, {"title": "Post-launch check and handover", "priority": "medium", "day": 62}]}]'::jsonb),
  ('SEO retainer', 'seo', 'Monthly SEO: audit, fix, publish, report.', '[{"name": "Audit", "tasks": [{"title": "Technical audit", "priority": "high", "day": 0}, {"title": "Keyword and competitor research", "priority": "medium", "day": 5}, {"title": "Google Business Profile review", "priority": "medium", "day": 7}]}, {"name": "Fix foundations", "tasks": [{"title": "Fix technical issues", "priority": "medium", "day": 14}, {"title": "Titles, descriptions and headings", "priority": "medium", "day": 18}, {"title": "Local listings and citations", "priority": "medium", "day": 24}]}, {"name": "Publish & optimize", "tasks": [{"title": "Publish priority pages and content", "priority": "medium", "day": 35}, {"title": "Internal links and schema", "priority": "medium", "day": 40}]}, {"name": "Monthly reporting", "tasks": [{"title": "Report: what changed and why", "priority": "high", "day": 60}, {"title": "Plan next month", "priority": "medium", "day": 62}]}]'::jsonb),
  ('Meta ads campaign', 'meta_ads', 'Facebook and Instagram ads: set up, launch, optimize.', '[{"name": "Strategy & tracking", "tasks": [{"title": "Goals, budget and offer", "priority": "high", "day": 0}, {"title": "Pixel and conversion tracking", "priority": "high", "day": 4}, {"title": "Audience plan", "priority": "medium", "day": 6}]}, {"name": "Creative", "tasks": [{"title": "Ad creative: images and video", "priority": "medium", "day": 12}, {"title": "Ad copy and landing page", "priority": "medium", "day": 14}, {"title": "Client approval", "priority": "high", "day": 17}]}, {"name": "Launch", "tasks": [{"title": "Build campaign and ad sets", "priority": "medium", "day": 19}, {"title": "Go live", "priority": "high", "day": 21}]}, {"name": "Optimize", "tasks": [{"title": "Review results at day 7", "priority": "medium", "day": 28}, {"title": "Pause losers, scale winners", "priority": "medium", "day": 35}]}, {"name": "Report", "tasks": [{"title": "Monthly results report", "priority": "high", "day": 50}]}]'::jsonb),
  ('Social media month', 'social', 'One month of social media management.', '[{"name": "Strategy", "tasks": [{"title": "Content pillars and tone", "priority": "medium", "day": 0}, {"title": "Posting calendar", "priority": "high", "day": 3}]}, {"name": "Content batch", "tasks": [{"title": "Write captions", "priority": "medium", "day": 7}, {"title": "Create graphics and clips", "priority": "medium", "day": 10}, {"title": "Client approval", "priority": "high", "day": 13}]}, {"name": "Schedule & post", "tasks": [{"title": "Schedule posts", "priority": "medium", "day": 15}, {"title": "Reply to comments and messages", "priority": "medium", "day": 30}]}, {"name": "Report", "tasks": [{"title": "Monthly social report", "priority": "high", "day": 30}]}]'::jsonb),
  ('Video content package', 'content', 'Short-form video from planning to delivery.', '[{"name": "Pre-production", "tasks": [{"title": "Concepts and shot list", "priority": "high", "day": 0}, {"title": "Book shoot date and location", "priority": "medium", "day": 3}, {"title": "Confirm props and release forms", "priority": "medium", "day": 6}]}, {"name": "Shoot", "tasks": [{"title": "Shoot day", "priority": "high", "day": 10}]}, {"name": "Edit", "tasks": [{"title": "First cut", "priority": "medium", "day": 14}, {"title": "Captions, music and branding", "priority": "medium", "day": 16}]}, {"name": "Approval & delivery", "tasks": [{"title": "Client review", "priority": "high", "day": 18}, {"title": "Revisions", "priority": "medium", "day": 21}, {"title": "Deliver final files and schedule posting", "priority": "medium", "day": 23}]}]'::jsonb)
on conflict (name) do nothing;

-- ▶ migrations/0026_passkeys.sql
-- ═══════════════════════════════════════════════════════════════════════════
-- Agency Zero — 0026: passkeys (WebAuthn) for CRM sign-in
--
-- Passkeys let an authorised CRM user sign in with the device's own unlock (fingerprint, face unlock, Windows Hello,
-- device PIN). The device does the biometric check; Agency Zero stores only the WebAuthn *public* credential:
-- never a fingerprint, a face template or a private key. Passwords keep working.
--
--   passkeys           — one row per registered passkey. The owner can see, rename and remove their own; rows are
--                        created ONLY by the server after it has verified a real WebAuthn attestation (no insert
--                        grant for browsers), and sign-in updates (counter, last_used_at) are made server-side.
--   passkey_challenges — short-lived, single-use challenges for registration and sign-in. Server only (no policies,
--                        no grants): the app reaches it with the service-role key.
--
-- Signing in with a passkey does NOT grant access by itself: the server still requires the account to be in
-- app_owner / app_team (the same rule as is_owner()) before it starts a session.
-- Reversible: `drop table public.passkey_challenges, public.passkeys;` (passwords are unaffected).
-- ═══════════════════════════════════════════════════════════════════════════

create table public.passkeys (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  credential_id text not null unique,
  public_key text not null,
  counter bigint not null default 0 check (counter >= 0),
  transports text[] not null default '{}',
  device_type text,
  backed_up boolean not null default false,
  name text not null check (length(trim(name)) between 1 and 80),
  created_at timestamptz not null default now(),
  last_used_at timestamptz
);
create index passkeys_user_idx on public.passkeys (user_id);

alter table public.passkeys enable row level security;

create policy "Owner sees own passkeys"
  on public.passkeys for select to authenticated
  using (user_id = (select auth.uid()) and public.is_owner());
create policy "Owner renames own passkeys"
  on public.passkeys for update to authenticated
  using (user_id = (select auth.uid()) and public.is_owner())
  with check (user_id = (select auth.uid()) and public.is_owner());
create policy "Owner removes own passkeys"
  on public.passkeys for delete to authenticated
  using (user_id = (select auth.uid()) and public.is_owner());

-- Browsers can read, rename and delete; they can never insert or change keys/counters.
revoke all on public.passkeys from anon, authenticated;
grant select, delete on public.passkeys to authenticated;
grant update (name) on public.passkeys to authenticated;

create table public.passkey_challenges (
  id uuid primary key default gen_random_uuid(),
  challenge text not null,
  purpose text not null check (purpose in ('register', 'login')),
  user_id uuid references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);
create index passkey_challenges_created_idx on public.passkey_challenges (created_at);

alter table public.passkey_challenges enable row level security;
revoke all on public.passkey_challenges from anon, authenticated;

commit;
