-- GENERATED by supabase/scripts/build-pending-migrations.sh — do not edit by hand.
-- Applies migrations 0014 → 0019 in ONE transaction (all or nothing).
-- Prerequisite: 0001–0013 already applied. If any of 0014+ was applied before, stop and ask.
-- Owner: 'drummerforger@gmail.com' becomes the Agency Zero owner (the migration aborts if that user does not exist).
begin;

-- ▶ migrations/0014_owner_only_rls.sql
-- ═══════════════════════════════════════════════════════════════════════════
-- Agency Zero — 0014: owner-only RLS (audit finding S1 / BUGS B-001)
--
-- Until now every policy was `auth.uid() is not null`, i.e. ANY authenticated
-- user was "the owner". That is only safe while Supabase public sign-ups are
-- disabled. This migration makes the database itself enforce single-owner
-- access, so an accidentally enabled sign-up (or an invited user) can no
-- longer read or write business data.
--
-- Design
--   * `public.app_owner` — singleton row holding the owner's auth user id.
--     RLS is enabled with NO policies: only the SECURITY DEFINER function
--     below can read it.
--   * Seeded from the oldest existing profile (the owner created first). On a
--     brand-new database the first user created becomes the owner
--     (`handle_new_user()` is updated accordingly).
--   * `public.is_owner()` — true when auth.uid() is the owner.
--   * Every policy that used the old "authenticated" predicate is rewritten to
--     `is_owner()`, including Storage policies for `client-files`.
--   * `profiles` keeps `id = auth.uid()` (a user can only see their own row).
--
-- !! BEFORE APPLYING TO PRODUCTION !!
--   Confirm the owner's profile is the OLDEST row in public.profiles:
--     select id, full_name, created_at from public.profiles order by created_at;
--   If not, fix the row after applying:
--     update public.app_owner set user_id = '<owner auth.users id>' where id = 1;
--   Applying this migration does not lock the owner out as long as that holds.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── owner registry ─────────────────────────────────────────────────────────
create table if not exists public.app_owner (
  id integer primary key default 1 check (id = 1),
  user_id uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

comment on table public.app_owner is
  'Singleton: the one auth user allowed to access business data. Read only via public.is_owner().';

alter table public.app_owner enable row level security;
-- Intentionally no policies: not readable or writable through the API.
revoke all on public.app_owner from anon, authenticated;

insert into public.app_owner (id, user_id)
select 1, p.id
from public.profiles p
order by p.created_at, p.id
limit 1
on conflict (id) do nothing;

create or replace function public.is_owner()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.app_owner o where o.user_id = (select auth.uid())
  );
$$;

revoke execute on function public.is_owner() from public;
grant execute on function public.is_owner() to anon, authenticated;

-- First user on an empty database becomes the owner; later sign-ups get a
-- profile row (harmless: RLS hides everything) but never ownership.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (
    new.id,
    coalesce(
      nullif(new.raw_user_meta_data ->> 'full_name', ''),
      split_part(coalesce(new.email, 'owner'), '@', 1)
    )
  );

  insert into public.settings (id) values (1) on conflict (id) do nothing;
  insert into public.app_owner (id, user_id) values (1, new.id) on conflict (id) do nothing;

  return new;
end;
$$;

revoke execute on function public.handle_new_user() from public, anon, authenticated;

-- ── rewrite every "any authenticated user" policy ─────────────────────────
do $$
declare
  pol record;
  using_clause text;
  check_clause text;
  rewritten integer := 0;
begin
  for pol in
    select schemaname, tablename, policyname, cmd
    from pg_policies
    where schemaname = 'public'
      and (coalesce(qual, '') ~* 'auth\.uid\(\).*is not null'
        or coalesce(with_check, '') ~* 'auth\.uid\(\).*is not null')
  loop
    using_clause := case when pol.cmd in ('ALL', 'SELECT', 'UPDATE', 'DELETE') then ' using (public.is_owner())' else '' end;
    check_clause := case when pol.cmd in ('ALL', 'INSERT', 'UPDATE') then ' with check (public.is_owner())' else '' end;
    execute format('alter policy %I on %I.%I%s%s',
      pol.policyname, pol.schemaname, pol.tablename, using_clause, check_clause);
    rewritten := rewritten + 1;
  end loop;
  raise notice '0014: rewrote % policies to is_owner()', rewritten;
end
$$;

-- ── Storage: client-files bucket ───────────────────────────────────────────
drop policy if exists "Owner reads client files" on storage.objects;
drop policy if exists "Owner uploads client files" on storage.objects;
drop policy if exists "Owner updates client files" on storage.objects;
drop policy if exists "Owner deletes client files" on storage.objects;

create policy "Owner reads client files"
  on storage.objects for select to authenticated
  using (bucket_id = 'client-files' and public.is_owner());
create policy "Owner uploads client files"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'client-files' and public.is_owner());
create policy "Owner updates client files"
  on storage.objects for update to authenticated
  using (bucket_id = 'client-files' and public.is_owner())
  with check (bucket_id = 'client-files' and public.is_owner());
create policy "Owner deletes client files"
  on storage.objects for delete to authenticated
  using (bucket_id = 'client-files' and public.is_owner());

-- ── SECURITY DEFINER RPCs that previously only checked auth.uid() ──────────
-- These bypass RLS, so they need the owner check themselves.
create or replace function public.convert_quote_to_project(p_quote_id uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare q public.quotes%rowtype; project_uuid uuid;
begin
  if not public.is_owner() then raise exception 'Authentication required'; end if;
  select * into q from public.quotes where id = p_quote_id for update;
  if not found then raise exception 'Quote not found'; end if;
  if q.status <> 'accepted' then raise exception 'Only accepted quotes can become projects'; end if;
  if q.converted_project_id is not null then return q.converted_project_id; end if;
  insert into public.projects (client_id, name, description, status, value_cents, currency, progress)
  values (q.client_id, q.title, 'Created from accepted quote ' || q.number, 'planning', q.total_cents, q.currency, 0)
  returning id into project_uuid;
  update public.quotes set converted_project_id = project_uuid where id = q.id;
  return project_uuid;
end;
$$;

create or replace function public.refresh_invoice_statuses()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_owner() then raise exception 'Authentication required'; end if;
  update public.invoices
  set status = 'overdue'::invoice_status
  where status in ('sent', 'partially_paid') and due_on < current_date and paid_cents < total_cents;
end;
$$;

-- ── safety net: fail the migration if any open policy remains ──────────────
do $$
declare leftover integer;
begin
  select count(*) into leftover
  from pg_policies
  where schemaname in ('public', 'storage')
    and 'authenticated' = any (roles)
    and (coalesce(qual, '') ~* 'auth\.uid\(\).*is not null'
      or coalesce(with_check, '') ~* 'auth\.uid\(\).*is not null');
  if leftover > 0 then
    raise exception '0014: % policies still use the any-authenticated predicate', leftover;
  end if;
end
$$;

-- ▶ make 'drummerforger@gmail.com' the owner explicitly (do not rely on "oldest profile")
do $$
declare v_id uuid;
begin
  select id into v_id from auth.users where lower(email) = lower('drummerforger@gmail.com') limit 1;
  if v_id is null then
    raise exception 'No auth user with email drummerforger@gmail.com — sign in once (or create the user) first, then re-run';
  end if;
  insert into public.app_owner (id, user_id) values (1, v_id)
  on conflict (id) do update set user_id = excluded.user_id;
end
$$;

-- ▶ migrations/0015_transactional_saves_and_invoice_protection.sql
-- ═══════════════════════════════════════════════════════════════════════════
-- Agency Zero — 0015: atomic quote/invoice saves + financial record protection
-- (audit BUGS B-004, B-005)
--
--   A. `save_quote()` / `save_invoice()` — header + line items in ONE
--      transaction. Previously the app deleted the lines, then inserted them,
--      then (for updates) had already rewritten the header; any failure left a
--      quote or invoice with missing or stale lines.
--      Both are SECURITY INVOKER, so RLS (owner-only, 0014) and the
--      accepted-quote immutability triggers (0008) still apply.
--   B. Invoices that are not drafts can no longer be deleted (void them), and
--      an invoice with payments can never be deleted: payments → invoice is
--      now ON DELETE RESTRICT instead of CASCADE.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── A. save_quote ──────────────────────────────────────────────────────────
create or replace function public.save_quote(
  p_id uuid,
  p_header jsonb,
  p_lines jsonb,
  p_token text default null,
  p_token_hash text default null
)
returns uuid
language plpgsql
security invoker
set search_path = public
as $$
declare
  h public.quotes%rowtype;
  v_id uuid;
begin
  if jsonb_typeof(p_lines) is distinct from 'array' then
    raise exception 'Line items must be a JSON array';
  end if;

  h := jsonb_populate_record(null::public.quotes, p_header);

  if p_id is null then
    if p_token is null or p_token_hash is null then
      raise exception 'A public token is required for new quotes';
    end if;
    insert into public.quotes (
      client_id, number, title, notes, status, issued_on, valid_until, currency,
      subtotal_cents, discount_cents, tax_rate, tax_cents, total_cents,
      public_token, public_token_hash
    ) values (
      h.client_id, h.number, h.title, h.notes, h.status, h.issued_on, h.valid_until, h.currency,
      h.subtotal_cents, h.discount_cents, h.tax_rate, h.tax_cents, h.total_cents,
      p_token, p_token_hash
    ) returning id into v_id;
  else
    update public.quotes q set
      client_id = h.client_id, number = h.number, title = h.title, notes = h.notes,
      status = h.status, issued_on = h.issued_on, valid_until = h.valid_until,
      currency = h.currency, subtotal_cents = h.subtotal_cents,
      discount_cents = h.discount_cents, tax_rate = h.tax_rate,
      tax_cents = h.tax_cents, total_cents = h.total_cents
    where q.id = p_id
    returning q.id into v_id;
    if v_id is null then raise exception 'Quote not found'; end if;
  end if;

  delete from public.quote_line_items where quote_id = v_id;
  insert into public.quote_line_items (
    quote_id, sort_order, service_id, description, details, qty, unit_amount_cents,
    is_recurring, billing_period, amount_cents, selection, option_group
  )
  select v_id, coalesce(l.sort_order, 0), l.service_id, l.description, l.details,
         coalesce(l.qty, 1), coalesce(l.unit_amount_cents, 0),
         coalesce(l.is_recurring, false), l.billing_period, coalesce(l.amount_cents, 0),
         coalesce(l.selection, 'fixed'), l.option_group
  from jsonb_populate_recordset(null::public.quote_line_items, p_lines) l;

  return v_id;
end;
$$;

-- ── A. save_invoice ────────────────────────────────────────────────────────
create or replace function public.save_invoice(
  p_id uuid,
  p_header jsonb,
  p_lines jsonb
)
returns uuid
language plpgsql
security invoker
set search_path = public
as $$
declare
  h public.invoices%rowtype;
  v_id uuid;
  v_paid integer;
begin
  if jsonb_typeof(p_lines) is distinct from 'array' then
    raise exception 'Line items must be a JSON array';
  end if;

  h := jsonb_populate_record(null::public.invoices, p_header);

  if p_id is null then
    insert into public.invoices (
      client_id, project_id, quote_id, contract_id, number, title, status,
      issued_on, due_on, currency, subtotal_cents, discount_cents, tax_cents,
      total_cents, deposit_cents, paid_cents, balance_cents
    ) values (
      h.client_id, h.project_id, h.quote_id, h.contract_id, h.number, h.title, h.status,
      h.issued_on, h.due_on, h.currency, h.subtotal_cents, h.discount_cents, h.tax_cents,
      h.total_cents, h.deposit_cents, 0, h.total_cents
    ) returning id into v_id;
  else
    select i.paid_cents into v_paid from public.invoices i where i.id = p_id for update;
    if not found then raise exception 'Invoice not found'; end if;
    if h.total_cents < v_paid then
      raise exception 'Invoice total cannot be lower than payments already recorded';
    end if;
    update public.invoices i set
      client_id = h.client_id, project_id = h.project_id, quote_id = h.quote_id,
      contract_id = h.contract_id, number = h.number, title = h.title, status = h.status,
      issued_on = h.issued_on, due_on = h.due_on, currency = h.currency,
      subtotal_cents = h.subtotal_cents, discount_cents = h.discount_cents,
      tax_cents = h.tax_cents, total_cents = h.total_cents,
      deposit_cents = h.deposit_cents, balance_cents = h.total_cents - v_paid
    where i.id = p_id
    returning i.id into v_id;
  end if;

  delete from public.invoice_line_items where invoice_id = v_id;
  insert into public.invoice_line_items (
    invoice_id, sort_order, description, qty, unit_amount_cents, amount_cents
  )
  select v_id, coalesce(l.sort_order, 0), l.description, coalesce(l.qty, 1),
         coalesce(l.unit_amount_cents, 0), coalesce(l.amount_cents, 0)
  from jsonb_populate_recordset(null::public.invoice_line_items, p_lines) l;

  return v_id;
end;
$$;

revoke execute on function public.save_quote(uuid, jsonb, jsonb, text, text) from public, anon;
revoke execute on function public.save_invoice(uuid, jsonb, jsonb) from public, anon;
grant execute on function public.save_quote(uuid, jsonb, jsonb, text, text) to authenticated;
grant execute on function public.save_invoice(uuid, jsonb, jsonb) to authenticated;

-- ── B. financial record protection ─────────────────────────────────────────
do $$
declare fk text;
begin
  select c.conname into fk
  from pg_constraint c
  where c.conrelid = 'public.payments'::regclass
    and c.contype = 'f'
    and c.confrelid = 'public.invoices'::regclass;
  if fk is not null then
    execute format('alter table public.payments drop constraint %I', fk);
  end if;
  alter table public.payments
    add constraint payments_invoice_id_fkey
    foreign key (invoice_id) references public.invoices (id) on delete restrict;
end
$$;

create or replace function public.protect_issued_invoice()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if old.status <> 'draft' then
    raise exception 'Only draft invoices can be deleted. Void the invoice instead.';
  end if;
  return old;
end;
$$;

drop trigger if exists invoices_protect_issued on public.invoices;
create trigger invoices_protect_issued
  before delete on public.invoices
  for each row execute function public.protect_issued_invoice();

revoke execute on function public.protect_issued_invoice() from public, anon, authenticated;

-- ▶ migrations/0016_payment_ledger_and_signature_evidence.sql
-- ═══════════════════════════════════════════════════════════════════════════
-- Agency Zero — 0016: permanent payment ledger + e-signature evidence
-- (audit BUGS B-011, finding S3)
--
--   A. Payments are never deleted or edited. A mistaken payment is VOIDED
--      (`voided_at` + mandatory `void_reason`); voided rows stay in the ledger,
--      are excluded from invoice totals, and a void cannot be undone (record a
--      new payment instead). Enforced by a trigger, so it holds for every
--      client, not just this app.
--   B. Invoice status is re-derived correctly when a payment is voided
--      (e.g. `paid` → `partially_paid`/`sent`).
--   C. The client and project workspace read models also return `voided_at`
--      for each payment (patched in place so 0012/0013 stay untouched).
--   D. Contract signatures now capture evidence: IP address, user agent, the
--      exact consent statement shown, and a SHA-256 of the signed body.
--      Signed contracts remain immutable, including the new columns.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── A. payment ledger ──────────────────────────────────────────────────────
alter table public.payments
  add column if not exists voided_at timestamptz,
  add column if not exists void_reason text;

alter table public.payments drop constraint if exists payments_void_reason_check;
alter table public.payments
  add constraint payments_void_reason_check
  check (voided_at is null or length(trim(coalesce(void_reason, ''))) > 0);

create or replace function public.protect_payment_ledger()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if tg_op = 'DELETE' then
    raise exception 'Payments are permanent records and cannot be deleted. Void the payment instead.';
  end if;
  if new.invoice_id is distinct from old.invoice_id
    or new.amount_cents is distinct from old.amount_cents
    or new.paid_on is distinct from old.paid_on
    or new.method is distinct from old.method
    or new.kind is distinct from old.kind
    or new.reference is distinct from old.reference
    or new.created_at is distinct from old.created_at
  then
    raise exception 'Payment details cannot be edited. Void the payment and record a new one.';
  end if;
  if old.voided_at is not null
    and (new.voided_at is distinct from old.voided_at or new.void_reason is distinct from old.void_reason)
  then
    raise exception 'A voided payment cannot be changed or restored. Record a new payment instead.';
  end if;
  return new;
end;
$$;

drop trigger if exists payments_protect_ledger on public.payments;
create trigger payments_protect_ledger
  before update or delete on public.payments
  for each row execute function public.protect_payment_ledger();

revoke execute on function public.protect_payment_ledger() from public, anon, authenticated;

-- ── B. recalculation ignores voided payments and un-sticks invoice status ──
create or replace function public.recalculate_invoice_payment()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  invoice_uuid uuid;
  paid integer;
  total integer;
  due date;
  current_status invoice_status;
begin
  invoice_uuid := coalesce(new.invoice_id, old.invoice_id);
  select i.total_cents, i.due_on, i.status into total, due, current_status
  from public.invoices i where i.id = invoice_uuid;
  select coalesce(sum(p.amount_cents), 0)::integer into paid
  from public.payments p where p.invoice_id = invoice_uuid and p.voided_at is null;
  update public.invoices
  set paid_cents = paid,
      balance_cents = total - paid,
      status = case
        when current_status = 'void' then 'void'::invoice_status
        when total > 0 and paid >= total then 'paid'::invoice_status
        when paid > 0 then 'partially_paid'::invoice_status
        when current_status in ('paid', 'partially_paid') then 'sent'::invoice_status
        when due < current_date and current_status in ('sent', 'overdue') then 'overdue'::invoice_status
        else current_status
      end
  where id = invoice_uuid;
  return coalesce(new, old);
end;
$$;

revoke execute on function public.recalculate_invoice_payment() from public, anon, authenticated;

-- ── C. read models expose voided_at ────────────────────────────────────────
do $$
declare
  fn text;
  def text;
  patched text;
begin
  foreach fn in array array['public.get_client_workspace(uuid)', 'public.get_project_workspace(uuid)']
  loop
    def := pg_get_functiondef(fn::regprocedure);
    patched := replace(def, '''method'', pm.method, ''kind'', pm.kind', '''method'', pm.method, ''kind'', pm.kind, ''voided_at'', pm.voided_at');
    if patched = def then
      raise exception '0016: could not patch % (payments projection changed)', fn;
    end if;
    execute patched;
  end loop;
end
$$;

-- ── D. signature evidence ──────────────────────────────────────────────────
alter table public.contracts
  add column if not exists signer_ip text,
  add column if not exists signer_user_agent text,
  add column if not exists consent_text text,
  add column if not exists signed_body_sha256 text;

create or replace function public.protect_signed_contract()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if old.status = 'signed'::public.contract_status then
    if tg_op = 'DELETE' then
      raise exception 'Signed contracts cannot be deleted; they are a permanent record.';
    end if;
    if new.status is distinct from old.status
      or new.client_id is distinct from old.client_id
      or new.title is distinct from old.title
      or new.body is distinct from old.body
      or new.template_id is distinct from old.template_id
      or new.version is distinct from old.version
      or new.viewed_at is distinct from old.viewed_at
      or new.signed_at is distinct from old.signed_at
      or new.signer_name is distinct from old.signer_name
      or new.signed_snapshot is distinct from old.signed_snapshot
      or new.signed_file_path is distinct from old.signed_file_path
      or new.signer_ip is distinct from old.signer_ip
      or new.signer_user_agent is distinct from old.signer_user_agent
      or new.consent_text is distinct from old.consent_text
      or new.signed_body_sha256 is distinct from old.signed_body_sha256
    then
      raise exception 'Signed contracts are immutable.';
    end if;
  end if;
  return coalesce(new, old);
end;
$$;

-- Replace the 2-argument signer with one that records evidence.
drop function if exists public.sign_public_contract(text, text);

create or replace function public.sign_public_contract(
  p_token_hash text,
  p_signer_name text,
  p_signer_ip text default null,
  p_signer_user_agent text default null,
  p_consent_text text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare result jsonb;
begin
  if length(trim(p_signer_name)) < 2 or length(trim(p_signer_name)) > 160 then
    raise exception 'Enter a valid signer name';
  end if;
  update public.contracts
  set status = 'signed'::contract_status,
      signer_name = trim(p_signer_name),
      signed_at = now(),
      signed_snapshot = body,
      signed_body_sha256 = encode(sha256(convert_to(body, 'UTF8')), 'hex'),
      signer_ip = left(nullif(trim(p_signer_ip), ''), 64),
      signer_user_agent = left(nullif(trim(p_signer_user_agent), ''), 400),
      consent_text = left(nullif(trim(p_consent_text), ''), 1000),
      viewed_at = coalesce(viewed_at, now())
  where public_token_hash = p_token_hash
    and (token_expires_at is null or token_expires_at > now())
    and status = 'sent';
  if not found then raise exception 'This contract is no longer available for signing'; end if;
  select jsonb_build_object('status', status, 'signed_at', signed_at, 'signer_name', signer_name)
    into result from public.contracts where public_token_hash = p_token_hash;
  return result;
end;
$$;

revoke execute on function public.sign_public_contract(text, text, text, text, text) from public;
grant execute on function public.sign_public_contract(text, text, text, text, text) to anon, authenticated;

-- ▶ migrations/0017_invoice_summary.sql
-- ═══════════════════════════════════════════════════════════════════════════
-- Agency Zero — 0017: invoice KPIs as a server-side aggregate
--
-- The invoices page computed its KPIs by summing the rows it had loaded. Once
-- the list is bounded (audit B-008) that would understate revenue, and it also
-- counted void/draft invoices as "outstanding". This read model computes the
-- totals over ALL invoices in Postgres:
--   revenue     = money actually received (sum of non-voided payments, which is
--                 invoices.paid_cents, on every invoice including void ones)
--   outstanding = unpaid balance on issued, non-void invoices (draft excluded)
--   overdue     = issued, non-void, balance > 0 and past due
-- Security invoker: RLS (owner-only) applies.
-- ═══════════════════════════════════════════════════════════════════════════
create or replace function public.get_invoice_summary(p_today date default null)
returns jsonb
language sql
stable
security invoker
set search_path = public
as $$
  select jsonb_build_object(
    'invoice_count', count(*),
    'revenue_cents', coalesce(sum(i.paid_cents), 0),
    'outstanding_cents', coalesce(sum(i.balance_cents) filter (where i.status not in ('draft', 'void')), 0),
    'overdue_count', count(*) filter (
      where i.status not in ('draft', 'void', 'paid')
        and i.balance_cents > 0
        and i.due_on < coalesce(p_today, current_date)
    ),
    'currency', coalesce((select i2.currency from public.invoices i2 order by i2.created_at desc limit 1), 'USD')
  )
  from public.invoices i;
$$;

revoke execute on function public.get_invoice_summary(date) from public, anon;
grant execute on function public.get_invoice_summary(date) to authenticated;

-- ▶ migrations/0018_team_access_and_revenue_summary.sql
-- ═══════════════════════════════════════════════════════════════════════════
-- Agency Zero — 0018: authorised team access + real revenue read model
--
--   A. `public.app_team` — users the owner explicitly authorises to use the
--      CRM. `public.is_owner()` (the single check behind every RLS policy and
--      the /app layout) now returns true for the owner OR a team member, so no
--      policy needs rewriting. The table has RLS enabled with no policies:
--      nobody can add themselves through the API. Grant access with SQL, e.g.
--        insert into public.app_team (user_id) select id from auth.users where email = 'person@example.com';
--      and revoke with `delete from public.app_team where user_id = '…';`.
--   B. `public.get_revenue_summary(p_today)` — money actually RECEIVED:
--        total_revenue_cents       = sum of every non-voided payment (one-time
--                                    jobs, deposits, installments, recurring)
--        revenue_this_month_cents  = same, paid_on within p_today's month
--        outstanding_cents         = unpaid balance on issued, non-void invoices
--      Quoted values, drafts and unpaid invoices never count as revenue.
--      Security invoker: RLS applies. `mixed_currency` is true when payments
--      exist in more than one currency (amounts are then not directly addable).
-- ═══════════════════════════════════════════════════════════════════════════

-- ── A. team access ─────────────────────────────────────────────────────────
create table if not exists public.app_team (
  user_id uuid primary key references auth.users (id) on delete cascade,
  role text not null default 'member' check (role in ('member')),
  granted_at timestamptz not null default now()
);

comment on table public.app_team is
  'Users explicitly authorised (by the owner, via SQL) to use the CRM. Not readable or writable through the API.';

alter table public.app_team enable row level security;
revoke all on public.app_team from anon, authenticated;

create or replace function public.is_owner()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.app_owner o where o.user_id = (select auth.uid()))
      or exists (select 1 from public.app_team t where t.user_id = (select auth.uid()));
$$;

revoke execute on function public.is_owner() from public;
grant execute on function public.is_owner() to anon, authenticated;

-- ── B. revenue summary ─────────────────────────────────────────────────────
create or replace function public.get_revenue_summary(p_today date default null)
returns jsonb
language sql
stable
security invoker
set search_path = public
as $$
  with bounds as (
    select date_trunc('month', coalesce(p_today, current_date))::date as month_start,
           (date_trunc('month', coalesce(p_today, current_date)) + interval '1 month')::date as month_end
  ),
  received as (
    select
      coalesce(sum(p.amount_cents), 0)::bigint as total_cents,
      coalesce(sum(p.amount_cents) filter (
        where p.paid_on >= b.month_start and p.paid_on < b.month_end
      ), 0)::bigint as month_cents,
      count(distinct i.currency) as currencies
    from public.payments p
    join public.invoices i on i.id = p.invoice_id
    cross join bounds b
    where p.voided_at is null
  ),
  owed as (
    select coalesce(sum(i.balance_cents), 0)::bigint as outstanding_cents
    from public.invoices i
    where i.status not in ('draft', 'void')
  )
  select jsonb_build_object(
    'total_revenue_cents', r.total_cents,
    'revenue_this_month_cents', r.month_cents,
    'outstanding_cents', o.outstanding_cents,
    'mixed_currency', r.currencies > 1,
    'currency', coalesce(
      (select i2.currency from public.invoices i2 order by i2.created_at desc limit 1),
      (select s.default_currency from public.settings s where s.id = 1),
      'USD')
  )
  from received r cross join owed o;
$$;

revoke execute on function public.get_revenue_summary(date) from public, anon;
grant execute on function public.get_revenue_summary(date) to authenticated;

-- ▶ migrations/0019_website_leads.sql
-- ═══════════════════════════════════════════════════════════════════════════
-- Agency Zero — 0019: website leads (public contact form → CRM)
--
-- The public site's project-inquiry form lands here. Design:
--   * `public.leads` is owner-only (RLS via is_owner()): nobody but the owner /
--     authorised team can read, edit or delete leads through the API.
--   * Anonymous visitors can ONLY call `public.submit_lead(...)` — a narrow
--     SECURITY DEFINER function that validates every field, whitelists the
--     service list, and rate-limits by a hashed submitter fingerprint and by
--     email (no raw IP is stored). It returns only the new id.
--   * `public.convert_lead_to_client(lead_id)` (security invoker, owner only)
--     turns a lead into a client + primary contact in one transaction.
-- ═══════════════════════════════════════════════════════════════════════════

create type public.lead_status as enum ('new', 'contacted', 'converted', 'dismissed');

create table public.leads (
  id uuid primary key default gen_random_uuid(),
  name text not null check (length(trim(name)) between 1 and 160),
  business text check (business is null or length(business) <= 200),
  email text not null check (length(email) <= 254 and position('@' in email) > 1),
  phone text check (phone is null or length(phone) <= 40),
  services text[] not null default '{}',
  budget text check (budget is null or length(budget) <= 60),
  details text check (details is null or length(details) <= 4000),
  source text not null default 'website',
  status public.lead_status not null default 'new',
  client_id uuid references public.clients (id) on delete set null,
  submitter_hash text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.leads is
  'Inbound project inquiries from the public website. Owner-only; written by submit_lead().';

create index leads_status_created_idx on public.leads (status, created_at desc);
create index leads_submitter_idx on public.leads (submitter_hash, created_at desc);
create index leads_email_idx on public.leads (lower(email), created_at desc);

alter table public.leads enable row level security;

create policy "Owner manages leads"
  on public.leads for all to authenticated
  using (public.is_owner()) with check (public.is_owner());

create trigger leads_set_updated_at
  before update on public.leads
  for each row execute function public.set_updated_at();

-- ── public submission ──────────────────────────────────────────────────────
create or replace function public.submit_lead(
  p_name text,
  p_business text,
  p_email text,
  p_phone text,
  p_services text[],
  p_budget text,
  p_details text,
  p_submitter_hash text default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
  v_name text := trim(coalesce(p_name, ''));
  v_email text := lower(trim(coalesce(p_email, '')));
  v_allowed text[] := array['software', 'websites', 'seo', 'meta-ads', 'social', 'content', 'not-sure'];
  v_services text[] := coalesce(p_services, '{}');
begin
  if length(v_name) < 1 or length(v_name) > 160 then raise exception 'Please enter your name'; end if;
  if length(v_email) > 254 or v_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then
    raise exception 'Please enter a valid email address';
  end if;
  if length(coalesce(p_details, '')) > 4000 then raise exception 'Project details are too long'; end if;
  if cardinality(v_services) > 8 or not (v_services <@ v_allowed) then raise exception 'Invalid service selection'; end if;

  -- Rate limits: protect the inbox and the database from floods.
  if (select count(*) from public.leads l where lower(l.email) = v_email and l.created_at > now() - interval '1 hour') >= 3 then
    raise exception 'Too many requests, please try again later';
  end if;
  if p_submitter_hash is not null
     and (select count(*) from public.leads l where l.submitter_hash = p_submitter_hash and l.created_at > now() - interval '1 hour') >= 5 then
    raise exception 'Too many requests, please try again later';
  end if;
  if (select count(*) from public.leads l where l.created_at > now() - interval '1 hour') >= 200 then
    raise exception 'Too many requests, please try again later';
  end if;

  insert into public.leads (name, business, email, phone, services, budget, details, submitter_hash)
  values (
    v_name,
    nullif(left(trim(coalesce(p_business, '')), 200), ''),
    v_email,
    nullif(left(trim(coalesce(p_phone, '')), 40), ''),
    v_services,
    nullif(left(trim(coalesce(p_budget, '')), 60), ''),
    nullif(trim(coalesce(p_details, '')), ''),
    left(p_submitter_hash, 128)
  )
  returning id into v_id;
  return v_id;
end;
$$;

revoke execute on function public.submit_lead(text, text, text, text, text[], text, text, text) from public;
grant execute on function public.submit_lead(text, text, text, text, text[], text, text, text) to anon, authenticated;

-- ── lead → client ──────────────────────────────────────────────────────────
create or replace function public.convert_lead_to_client(p_lead_id uuid)
returns uuid
language plpgsql
security invoker
set search_path = public
as $$
declare
  l public.leads%rowtype;
  v_client uuid;
begin
  select * into l from public.leads where id = p_lead_id for update;
  if not found then raise exception 'Lead not found'; end if;
  if l.client_id is not null then return l.client_id; end if;

  insert into public.clients (name, status, company, email, phone, source, notes_summary)
  values (
    coalesce(nullif(l.business, ''), l.name),
    'lead',
    nullif(l.business, ''),
    l.email,
    l.phone,
    'website',
    nullif(concat_ws(E'\n', 'Interested in: ' || nullif(array_to_string(l.services, ', '), ''), 'Budget: ' || l.budget, l.details), '')
  )
  returning id into v_client;

  insert into public.contacts (client_id, name, email, phone, is_primary)
  values (v_client, l.name, l.email, l.phone, true);

  update public.leads set status = 'converted', client_id = v_client where id = l.id;
  return v_client;
end;
$$;

revoke execute on function public.convert_lead_to_client(uuid) from public, anon;
grant execute on function public.convert_lead_to_client(uuid) to authenticated;

commit;
